import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 820 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5173');
await page.waitForSelector('text=w1-05', { timeout: 90000 });
await page.click('text=w1-05');
await page.click('text=The cheapest Class B in stock');
await page.click('.tab:has-text("Untangle")');
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/claude-0/shots/read.png' });
await page.click('text=✕ Exit');
await page.click('text=w1-09');
await page.waitForTimeout(1500);
const btns = page.locator('.choice');
await btns.nth(1).click();
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/claude-0/shots/predict.png' });
await browser.close();
