import type { Challenge, World } from '../types';

export const W1_CHALLENGES: Challenge[] = [
  {
    id: 'w1-01',
    world: 1,
    type: 'write',
    title: 'First Walk of the Lot',
    giver: 'rhonda',
    story: "Welcome to Summit Trail RV. Before you touch anything, walk the lot. Every RV we own lives in the `units` table.",
    question: 'Show the first 10 rows of the units table, all columns.',
    concepts: ['SELECT', 'LIMIT'],
    starter: 'SELECT *\nFROM units\n',
    solution: 'SELECT * FROM units LIMIT 10',
    check: 'shape',
    hints: [
      '`SELECT *` means "every column". You still need to say how many rows.',
      'LIMIT n goes at the very end and keeps only n rows.',
      'SELECT * FROM units LIMIT 10',
    ],
    why: "Peeking at 10 rows is how every analyst starts with an unfamiliar table. You learn the columns, the formats and the weirdness before writing anything big. (Here, row order isn't guaranteed, so any 10 rows count.)",
    codex: ['stock-number', 'vin', 'msrp-invoice'],
  },
  {
    id: 'w1-02',
    world: 1,
    type: 'write',
    title: "Where's N26-00084?",
    giver: 'scout',
    story: 'A customer on the phone says a salesperson told them about "stock number N26-00084". Can you pull it up so I can find it on the lot?',
    question: "Return the stock_no, model_year, manufacturer, model, rv_class and status for stock number 'N26-00084'.",
    concepts: ['WHERE', '= on text'],
    starter: 'SELECT stock_no, model_year, manufacturer, model, rv_class, status\nFROM units\nWHERE ',
    solution: "SELECT stock_no, model_year, manufacturer, model, rv_class, status FROM units WHERE stock_no = 'N26-00084'",
    expectedColumns: ['stock_no', 'model_year', 'manufacturer', 'model', 'rv_class', 'status'],
    hints: [
      'Filter rows with WHERE.',
      "Text values go in single quotes: WHERE stock_no = '...'",
      "…WHERE stock_no = 'N26-00084'",
    ],
    why: 'The stock number is the dealer\'s own ID for a unit. Salespeople, porters and accounting all use it, while the customer usually only knows the VIN or "the blue one by the fence".',
    codex: ['stock-number'],
  },
  {
    id: 'w1-03',
    world: 1,
    type: 'write',
    title: 'Diesel Pushers on Display',
    giver: 'tony',
    story: "A big-spender couple is coming in Saturday and they want a motorhome, a Class A. Show me every NEW Class A we have In Stock, fanciest first.",
    question: "List stock_no, model, location_id and msrp for units that are condition 'New', rv_class 'Class A' and status 'In Stock', highest MSRP first.",
    concepts: ['WHERE', 'AND', 'ORDER BY DESC'],
    starter: 'SELECT stock_no, model, location_id, msrp\nFROM units\nWHERE \n',
    solution:
      "SELECT stock_no, model, location_id, msrp FROM units WHERE condition = 'New' AND rv_class = 'Class A' AND status = 'In Stock' ORDER BY msrp DESC",
    orderMatters: true,
    expectedColumns: ['stock_no', 'model', 'location_id', 'msrp'],
    hints: [
      'Three conditions must all be true: chain them with AND.',
      'ORDER BY msrp sorts low→high. Add DESC for high→low.',
      "WHERE condition = 'New' AND rv_class = 'Class A' AND status = 'In Stock' ORDER BY msrp DESC",
    ],
    why: "Class A motorhomes are the most expensive units on the lot, so a handful of them can tie up a lot of floorplan money. Sales managers always want to know exactly which ones are sitting.",
    codex: ['rv-classes', 'msrp-invoice'],
  },
  {
    id: 'w1-04',
    world: 1,
    type: 'write',
    title: 'Who Builds Our Stuff?',
    giver: 'rhonda',
    story: "I've got a manufacturer rep meeting next week and I can never remember every brand we carry.",
    question: 'Return the list of different manufacturers in units, one row each, alphabetically.',
    concepts: ['DISTINCT', 'ORDER BY'],
    solution: 'SELECT DISTINCT manufacturer FROM units ORDER BY manufacturer',
    orderMatters: true,
    expectedColumns: ['manufacturer'],
    hints: [
      'You want each manufacturer once, no matter how many units they built.',
      'SELECT DISTINCT removes duplicate rows from the output.',
      'SELECT DISTINCT manufacturer FROM units ORDER BY manufacturer',
    ],
    why: 'Dealers hold franchise agreements with specific manufacturers. The "brands we carry" list matters for co-op advertising, warranty claims and floorplan programs.',
  },
  {
    id: 'w1-05',
    world: 1,
    type: 'read',
    title: 'Read the Sticker',
    giver: 'tony',
    story: 'My old sales manager left me this query on a sticky note. What does it show me?',
    question: 'Which row comes FIRST in this query\'s result?',
    concepts: ['IN', 'ORDER BY multiple columns'],
    query:
      "SELECT stock_no, rv_class, msrp\nFROM units\nWHERE rv_class IN ('Class B', 'Class C')\n  AND status = 'In Stock'\nORDER BY rv_class, msrp DESC",
    choices: [
      'The cheapest Class B in stock',
      'The most expensive Class B in stock',
      'The most expensive Class C in stock',
      'The most expensive unit of any class',
    ],
    answer: 1,
    explanations: [
      'msrp is sorted DESC, so the cheapest Class B is at the END of the Class B block.',
      "Yes! ORDER BY rv_class sorts alphabetically first ('Class B' before 'Class C'), then msrp DESC puts the priciest Class B on top.",
      "'Class C' sorts after 'Class B', so the Class C rows come second.",
      'Only Class B and Class C pass the WHERE, and rv_class is sorted before msrp.',
    ],
    hints: [
      'ORDER BY with two columns sorts by the first, and only uses the second to break ties.',
      "Alphabetically, which comes first: 'Class B' or 'Class C'?",
      'Within the first class, DESC means highest msrp first.',
    ],
    why: 'Multi-column sorts show up in every inventory report ("by class, then by price"). Reading the ORDER BY left to right tells you how the report is organized.',
    codex: ['rv-classes'],
  },
  {
    id: 'w1-06',
    world: 1,
    type: 'write',
    title: 'Spring Shipments',
    giver: 'marge',
    story: "The manufacturer says they shipped us a pile of units in Q1. I want to see what actually arrived between January 1 and March 31, 2026.",
    question: 'Return stock_no, manufacturer, rv_class and received_date for units received from 2026-01-01 through 2026-03-31 (inclusive), earliest first.',
    concepts: ['BETWEEN', 'dates'],
    solution:
      "SELECT stock_no, manufacturer, rv_class, received_date FROM units WHERE received_date BETWEEN DATE '2026-01-01' AND DATE '2026-03-31' ORDER BY received_date, stock_no",
    orderMatters: false,
    expectedColumns: ['stock_no', 'manufacturer', 'rv_class', 'received_date'],
    hints: [
      'BETWEEN a AND b includes both ends.',
      "Dates can be written as DATE '2026-01-01' (or just '2026-01-01').",
      "WHERE received_date BETWEEN DATE '2026-01-01' AND DATE '2026-03-31' ORDER BY received_date",
    ],
    why: "Arrival dates start the aging clock and trigger the PDI work order. Controllers compare them against the floorplan funding dates, because interest often starts before the unit even arrives.",
    codex: ['floorplan', 'aging'],
    snowflake: [
      {
        title: 'Date literals',
        snowflake: "WHERE received_date BETWEEN '2026-01-01'::DATE AND '2026-03-31'::DATE",
        duckdb: "WHERE received_date BETWEEN DATE '2026-01-01' AND DATE '2026-03-31'",
        note: "Both engines also accept plain '2026-01-01' strings compared to a DATE column.",
      },
    ],
  },
  {
    id: 'w1-07',
    world: 1,
    type: 'write',
    title: 'The Last Six',
    giver: 'scout',
    story: "A customer is reading a VIN off their paperwork but only has the last six characters: 471800. Which unit is it?",
    question: "Find the stock_no, vin, rv_class and status of the unit whose VIN ends in '471800'.",
    concepts: ['LIKE', 'wildcards'],
    solution: "SELECT stock_no, vin, rv_class, status FROM units WHERE vin LIKE '%471800'",
    expectedColumns: ['stock_no', 'vin', 'rv_class', 'status'],
    hints: [
      'LIKE matches patterns. % means "any characters (or none)".',
      "'%471800' means: anything, then 471800 at the end.",
      "WHERE vin LIKE '%471800'",
    ],
    why: 'The last 6 of the VIN is the serial number part. Service advisors and title clerks search by it constantly.',
    codex: ['vin'],
    snowflake: [
      {
        title: 'Case-insensitive matching',
        snowflake: "WHERE vin ILIKE '%abc123'",
        duckdb: "WHERE vin ILIKE '%abc123'",
        note: 'ILIKE works the same in both. LIKE is case-sensitive in both.',
      },
    ],
  },
  {
    id: 'w1-08',
    world: 1,
    type: 'fix',
    title: 'The Units That Never Arrived',
    giver: 'devin',
    story: "Some unit records have no received_date. That's either In Transit (fine) or bad data (not fine). My query to find them returns nothing, and I *know* they exist.",
    question: 'Fix the query so it returns the stock_no and status of every unit with a missing received_date.',
    concepts: ['NULL', 'IS NULL'],
    starter: 'SELECT stock_no, status\nFROM units\nWHERE received_date = NULL',
    solution: 'SELECT stock_no, status FROM units WHERE received_date IS NULL',
    expectedColumns: ['stock_no', 'status'],
    hints: [
      'NULL means "unknown". Is unknown equal to unknown? SQL says: unknown.',
      '`= NULL` never evaluates to TRUE, so every row is filtered out.',
      'Use WHERE received_date IS NULL.',
    ],
    why: "Look at the statuses: In Transit units legitimately have no arrival date, but a few Sold and In Stock units are missing one too. That's a data-quality issue to flag, because aging reports can't age a unit with no start date.",
    codex: ['null'],
  },
  {
    id: 'w1-09',
    world: 1,
    type: 'predict',
    title: 'Count Before You Run',
    giver: 'tony',
    story: "Quick, gut check! Before you hit RUN: how many rows will this return?",
    question: 'Predict the number of rows.',
    concepts: ['WHERE', 'AND'],
    query: "SELECT stock_no, model\nFROM units\nWHERE location_id = 1\n  AND condition = 'Used'\n  AND rv_class = 'Travel Trailer'\n  AND status = 'In Stock'",
    measure: 'rows',
    decoys: [
      { sql: "SELECT count(*) FROM units WHERE location_id = 1 AND rv_class = 'Travel Trailer' AND status = 'In Stock'", why: 'That counts new AND used travel trailers.' },
      { sql: "SELECT count(*) FROM units WHERE location_id = 1 AND condition = 'Used' AND rv_class = 'Travel Trailer'", why: 'That forgets the status filter, so it includes the sold and wholesaled ones.' },
      { sql: "SELECT count(*) FROM units WHERE condition = 'Used' AND rv_class = 'Travel Trailer' AND status = 'In Stock'", why: 'That counts every store, not just Denver (location 1).' },
    ],
    explanation: 'Every AND narrows the result: Denver, used, travel trailer, and still in stock.',
    hints: [
      'Each AND condition removes rows. All four must be true.',
      'Denver is a mid-size store; used towables are common.',
      "It's a small number: somewhere under 10.",
    ],
    why: 'Estimating a result before running is a superpower: if the real answer is wildly different, you instantly know your query (or the data) has a problem.',
  },
  {
    id: 'w1-10',
    world: 1,
    type: 'write',
    title: 'Markup Check',
    giver: 'marge',
    story: 'Show me the ten units with the biggest gap between sticker (MSRP) and what we paid (invoice). Label the gap "markup".',
    question: 'Return stock_no, msrp, invoice_cost and markup (msrp − invoice_cost) for the 10 units with the largest markup, largest first.',
    concepts: ['calculated columns', 'aliases', 'ORDER BY alias', 'LIMIT'],
    solution: 'SELECT stock_no, msrp, invoice_cost, msrp - invoice_cost AS markup FROM units ORDER BY markup DESC LIMIT 10',
    orderMatters: true,
    expectedColumns: ['stock_no', 'msrp', 'invoice_cost', 'markup'],
    hints: [
      'You can do math in SELECT: msrp - invoice_cost.',
      'Name a computed column with AS markup. You can ORDER BY that name.',
      'SELECT stock_no, msrp, invoice_cost, msrp - invoice_cost AS markup FROM units ORDER BY markup DESC LIMIT 10',
    ],
    why: "MSRP minus invoice is the *potential* margin. Almost nobody pays sticker, though. The real profit is front-end gross, which you'll meet in the F&I Office.",
    codex: ['msrp-invoice', 'front-gross'],
  },

  // ---- boss questions ----------------------------------------------------------
  {
    id: 'w1-mb-1',
    world: 1,
    type: 'write',
    bossOnly: true,
    title: 'Shuffle 1',
    giver: 'scout',
    story: 'The Shuffler swapped the stickers! Which unit has VIN ending in 139065?',
    question: "Return the stock_no of the unit whose VIN ends in '139065'.",
    concepts: ['LIKE'],
    solution: "SELECT stock_no FROM units WHERE vin LIKE '%139065'",
    hints: ['LIKE with %', "vin LIKE '%139065'", "SELECT stock_no FROM units WHERE vin LIKE '%139065'"],
    why: 'Last-6 lookups are an everyday task.',
  },
  {
    id: 'w1-mb-2',
    world: 1,
    type: 'write',
    bossOnly: true,
    title: 'Shuffle 2',
    giver: 'scout',
    story: 'It hid every Class B at Denver (location 1)!',
    question: "Return stock_no and status for all Class B units at location_id 1.",
    concepts: ['WHERE', 'AND'],
    solution: "SELECT stock_no, status FROM units WHERE rv_class = 'Class B' AND location_id = 1",
    hints: ['Two conditions.', "rv_class = 'Class B' AND location_id = 1", "SELECT stock_no, status FROM units WHERE rv_class = 'Class B' AND location_id = 1"],
    why: 'Filtering by class and store is the bread and butter of inventory work.',
  },
  {
    id: 'w1-mb-3',
    world: 1,
    type: 'write',
    bossOnly: true,
    title: 'Shuffle 3',
    giver: 'scout',
    story: 'Last trick: which statuses exist at all?',
    question: 'Return each different unit status once.',
    concepts: ['DISTINCT'],
    solution: 'SELECT DISTINCT status FROM units',
    hints: ['One row per status.', 'DISTINCT', 'SELECT DISTINCT status FROM units'],
    why: 'Checking the distinct values of a column is the fastest way to learn what a field can contain.',
  },
  {
    id: 'w1-b-1',
    world: 1,
    type: 'write',
    bossOnly: true,
    title: 'Gremlin Phase 1',
    giver: 'devin',
    story: 'The Null Gremlin is hiding units with no arrival date. Expose the ones that are NOT In Transit (those are the real bad records).',
    question: "Return stock_no and status for units with a NULL received_date whose status is not 'In Transit'.",
    concepts: ['IS NULL', '<>'],
    solution: "SELECT stock_no, status FROM units WHERE received_date IS NULL AND status <> 'In Transit'",
    hints: ['IS NULL, not = NULL.', "Combine with status <> 'In Transit'.", "WHERE received_date IS NULL AND status <> 'In Transit'"],
    why: 'Separating legitimate NULLs from bad-data NULLs is a daily data-quality task.',
  },
  {
    id: 'w1-b-2',
    world: 1,
    type: 'predict',
    bossOnly: true,
    title: 'Gremlin Phase 2',
    giver: 'devin',
    story: 'The Gremlin taunts you: "COUNT(*) and COUNT(column) are the same thing!" Are they?',
    question: 'What number does this return?',
    concepts: ['COUNT(*) vs COUNT(col)'],
    query: 'SELECT COUNT(*) - COUNT(received_date) AS gap\nFROM units',
    measure: 'value',
    decoys: [
      { sql: 'SELECT 0', why: 'COUNT(column) skips NULLs, so the two counts differ.' },
      { sql: 'SELECT count(*) FROM units', why: 'That would mean every received_date is NULL.' },
      { sql: "SELECT count(*) FROM units WHERE status = 'In Transit'", why: 'Close, but a few non-transit units are missing dates too.' },
    ],
    explanation: 'COUNT(*) counts rows; COUNT(received_date) counts only non-NULL values. The gap is the number of NULL received dates.',
    hints: ['COUNT(column) ignores NULLs.', 'So the difference = number of NULLs.', 'In Transit units plus a few bad records.'],
    why: 'Mixing up COUNT(*) and COUNT(col) is one of the most common silent bugs in reporting.',
  },
  {
    id: 'w1-b-3',
    world: 1,
    type: 'write',
    bossOnly: true,
    title: 'Gremlin Phase 3',
    giver: 'devin',
    story: 'Final blow: the recon report shows blanks where recon_cost is NULL. Marge wants zeros instead.',
    question: 'Return stock_no and recon_cost for every Used unit, showing 0 when recon_cost is NULL. Call the column recon_cost.',
    concepts: ['COALESCE'],
    solution: "SELECT stock_no, COALESCE(recon_cost, 0) AS recon_cost FROM units WHERE condition = 'Used'",
    hints: ['COALESCE(a, b) returns a, or b if a is NULL.', "Filter condition = 'Used'.", "SELECT stock_no, COALESCE(recon_cost, 0) AS recon_cost FROM units WHERE condition = 'Used'"],
    why: 'COALESCE is how you give NULLs a sensible default in reports. Snowflake also has IFNULL/NVL for two arguments.',
    snowflake: [{ title: 'NULL defaults', snowflake: 'NVL(recon_cost, 0)  -- or IFNULL / COALESCE', duckdb: 'COALESCE(recon_cost, 0)  -- IFNULL also works' }],
  },
];

export const WORLD_1: World = {
  id: 1,
  name: 'The Lot',
  building: 'lot',
  giver: 'rhonda',
  tagline: 'SELECT, WHERE, ORDER BY, LIMIT, DISTINCT, LIKE, BETWEEN, NULL',
  concepts: ['SELECT', 'WHERE', 'ORDER BY', 'LIMIT', 'DISTINCT', 'LIKE', 'BETWEEN', 'NULL'],
  lesson: [
    {
      title: 'The lot is a table',
      body: 'Every RV the dealership owns is one row in `units`. The stock number (stock_no) is our ID for it; the VIN is the manufacturer\'s. New units are bought from the factory (MSRP is the sticker, invoice_cost is what we paid). Used units mostly arrive as trade-ins.',
    },
    {
      title: 'Reading a basic query',
      body: 'Read SELECT queries in this order: FROM (which table?) → WHERE (which rows?) → SELECT (which columns?) → ORDER BY (in what order?) → LIMIT (how many?).',
      sql: "SELECT stock_no, msrp        -- 3. show these columns\nFROM units                  -- 1. from this table\nWHERE status = 'In Stock'   -- 2. keep these rows\nORDER BY msrp DESC          -- 4. priciest first\nLIMIT 5                     -- 5. just the top 5",
    },
    {
      title: 'NULL is not a value',
      body: "NULL means unknown or missing. Nothing equals NULL, not even NULL. Use IS NULL / IS NOT NULL. Units that are In Transit have a NULL received_date because they haven't arrived yet.",
    },
  ],
  challenges: ['w1-01', 'w1-02', 'w1-03', 'w1-04', 'w1-05', 'w1-06', 'w1-07', 'w1-08', 'w1-09', 'w1-10'],
  miniBoss: {
    id: 'w1-mini',
    name: 'The Stock Number Shuffler',
    sprite: 'shuffler',
    mini: true,
    intro: 'A blur of swapped window stickers! The Shuffler has mixed up every stock number on the lot!',
    victory: 'The stickers flutter back onto the right windshields. Scout gives you a thumbs up.',
    timer: 120,
    phases: [{ name: 'Sticker Storm', taunt: 'Catch me if you can!', questions: ['w1-mb-1', 'w1-mb-2', 'w1-mb-3'] }],
  },
  boss: {
    id: 'w1-boss',
    name: 'The Null Gremlin',
    sprite: 'gremlin',
    mini: false,
    intro: 'Rows vanish from reports. Blanks appear where numbers should be. The Null Gremlin feeds on missing values and `= NULL` bugs!',
    victory: 'With a sad little squeak, the Gremlin evaporates into a puff of IS NOT NULL. Devin applauds from the doorway.',
    timer: 150,
    phases: [
      { name: 'Hidden Rows', taunt: 'You\'ll never find what isn\'t there!', questions: ['w1-b-1'] },
      { name: 'Counting Tricks', taunt: 'COUNT(*) and COUNT(col) are twins, hehehe!', questions: ['w1-b-2'] },
      { name: 'Blank Report', taunt: 'Blanks everywhere! The Controller will be SO mad!', questions: ['w1-b-3'] },
    ],
  },
};
