import type { Challenge, World } from '../types';

const FUNDED = "deal_status = 'Funded'";

export const W2_CHALLENGES: Challenge[] = [
  {
    id: 'w2-01',
    world: 2,
    type: 'write',
    title: 'Scoreboard',
    giver: 'tony',
    story: "Every Monday I put the store scoreboard up on the whiteboard. Units sold, by store. Let's automate it!",
    question: "For funded deals only, return location_id and the number of deals (call it units_sold), biggest store first.",
    concepts: ['GROUP BY', 'COUNT', 'ORDER BY'],
    starter: "SELECT location_id, COUNT(*) AS units_sold\nFROM deals\nWHERE deal_status = 'Funded'\n",
    solution: `SELECT location_id, COUNT(*) AS units_sold FROM deals WHERE ${FUNDED} GROUP BY location_id ORDER BY units_sold DESC, location_id`,
    orderMatters: false,
    expectedColumns: ['location_id', 'units_sold'],
    hints: [
      'COUNT(*) counts rows, but you need one count per store.',
      'GROUP BY location_id makes one group (and one output row) per store.',
      "…WHERE deal_status = 'Funded' GROUP BY location_id ORDER BY units_sold DESC",
    ],
    why: "Only funded deals are money in the bank. Pending contracts can still fall apart, and unwound deals didn't happen at all. Most dealer scoreboards count funded (or at least non-unwound) deals.",
    codex: ['funded', 'unwind'],
  },
  {
    id: 'w2-02',
    world: 2,
    type: 'write',
    title: 'Month by Month',
    giver: 'tony',
    story: 'RVs are seasonal. Spring is crazy, winter is quiet. Show me units sold every month so I can see the waves.',
    question: 'Return month (the deal_date truncated to the month) and units (funded deals), oldest month first.',
    concepts: ['DATE_TRUNC', 'GROUP BY', 'dates'],
    solution: `SELECT DATE_TRUNC('month', deal_date) AS month, COUNT(*) AS units FROM deals WHERE ${FUNDED} GROUP BY month ORDER BY month`,
    orderMatters: true,
    expectedColumns: ['month', 'units'],
    hints: [
      "DATE_TRUNC('month', deal_date) turns 2025-04-17 into 2025-04-01.",
      'Group by that truncated value, and order by it too.',
      "SELECT DATE_TRUNC('month', deal_date) AS month, COUNT(*) AS units FROM deals WHERE deal_status = 'Funded' GROUP BY month ORDER BY month",
    ],
    why: 'Monthly unit trends drive inventory orders, staffing and floorplan planning. Winter months are slow in most RV markets, and RV-show season (Jan–Mar) fills the spring pipeline.',
    snowflake: [{ title: 'Truncating dates', snowflake: "DATE_TRUNC('month', deal_date)", duckdb: "DATE_TRUNC('month', deal_date)", note: 'Identical. Snowflake returns a DATE for DATE input; DuckDB may return a TIMESTAMP at midnight, and the checker treats them as equal.' }],
  },
  {
    id: 'w2-03',
    world: 2,
    type: 'write',
    title: 'Who Holds Gross?',
    giver: 'tony',
    story: "Volume is nice, but gross pays the bills. Who's holding the most front-end gross per deal?",
    question: 'For funded deals, return salesperson_id, deals (count) and avg_front_gross (average front_gross), highest average first.',
    concepts: ['AVG', 'COUNT', 'GROUP BY'],
    solution: `SELECT salesperson_id, COUNT(*) AS deals, AVG(front_gross) AS avg_front_gross FROM deals WHERE ${FUNDED} GROUP BY salesperson_id ORDER BY avg_front_gross DESC`,
    orderMatters: true,
    expectedColumns: ['salesperson_id', 'deals', 'avg_front_gross'],
    hints: [
      'Two aggregates in one SELECT: COUNT(*) and AVG(front_gross).',
      'Group by salesperson_id and sort by the average, descending.',
      "SELECT salesperson_id, COUNT(*) AS deals, AVG(front_gross) AS avg_front_gross FROM deals WHERE deal_status = 'Funded' GROUP BY salesperson_id ORDER BY avg_front_gross DESC",
    ],
    why: "Notice anything odd? There's a salesperson_id of -1 with a bunch of deals. That's not a person, it's a 'sentinel' for unknown. Data Detective HQ will deal with that. Also: an average over 1 deal isn't a trend, so always show the count next to an average.",
    codex: ['front-gross', 'sentinel'],
  },
  {
    id: 'w2-04',
    world: 2,
    type: 'write',
    title: 'Where Leads Come From',
    giver: 'tony',
    story: 'Marketing wants to know which lead sources are pulling their weight. Start simple: how many leads from each source?',
    question: 'Return source and leads (count of leads), most leads first.',
    concepts: ['GROUP BY', 'COUNT'],
    solution: 'SELECT source, COUNT(*) AS leads FROM leads GROUP BY source ORDER BY leads DESC',
    orderMatters: true,
    expectedColumns: ['source', 'leads'],
    hints: ['One row per source.', 'GROUP BY source, then COUNT(*).', 'SELECT source, COUNT(*) AS leads FROM leads GROUP BY source ORDER BY leads DESC'],
    why: 'Lead volume alone is misleading: websites generate tons of leads that rarely buy. You need volume AND close rate. That comes next.',
    codex: ['lead-source'],
  },
  {
    id: 'w2-05',
    world: 2,
    type: 'write',
    title: 'Close Rate by Source',
    giver: 'tony',
    story: 'OK, now the real question. Which sources actually BUY? I want the close rate for each lead source.',
    question: "Return source, leads (count), sold (leads with status 'Sold') and close_rate_pct (100 × sold ÷ leads), best close rate first.",
    concepts: ['COUNT_IF', 'conditional count', 'GROUP BY'],
    solution:
      "SELECT source, COUNT(*) AS leads, COUNT_IF(status = 'Sold') AS sold, 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM leads GROUP BY source ORDER BY close_rate_pct DESC",
    orderMatters: true,
    expectedColumns: ['source', 'leads', 'sold', 'close_rate_pct'],
    hints: [
      "COUNT_IF(status = 'Sold') counts only the rows where the condition is true.",
      'Close rate = sold ÷ leads. Multiply by 100.0 (with the .0!) to get a percent without integer division.',
      "SELECT source, COUNT(*) AS leads, COUNT_IF(status = 'Sold') AS sold, 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM leads GROUP BY source ORDER BY close_rate_pct DESC",
    ],
    why: 'Referrals and walk-ins close far better than third-party marketplace leads. That is typical, and it is why dealers invest in customer experience (referrals) even though it is hard to measure. Keep this query handy: the duplicate leads in Data Detective HQ will change these numbers.',
    codex: ['close-rate'],
    snowflake: [{ title: 'Conditional counts', snowflake: "COUNT_IF(status = 'Sold')", duckdb: "COUNT_IF(status = 'Sold')  -- also: COUNT(*) FILTER (WHERE status = 'Sold')" }],
  },
  {
    id: 'w2-06',
    world: 2,
    type: 'fix',
    title: 'The Big Stores',
    giver: 'tony',
    story: 'I want the stores that did more than 100 deals. My query blows up with an error about aggregates.',
    question: 'Fix the query: return location_id and deals for stores with more than 100 deals (all statuses).',
    concepts: ['HAVING', 'WHERE vs HAVING'],
    starter: 'SELECT location_id, COUNT(*) AS deals\nFROM deals\nWHERE COUNT(*) > 100\nGROUP BY location_id',
    solution: 'SELECT location_id, COUNT(*) AS deals FROM deals GROUP BY location_id HAVING COUNT(*) > 100',
    expectedColumns: ['location_id', 'deals'],
    hints: [
      'WHERE runs BEFORE grouping, so there are no counts yet.',
      'Filters on aggregates go in HAVING, which runs after GROUP BY.',
      'Move the condition: … GROUP BY location_id HAVING COUNT(*) > 100',
    ],
    why: 'WHERE filters rows, HAVING filters groups. Mixing them up is one of the most common SQL errors, and X-Ray shows exactly when each one runs.',
  },
  {
    id: 'w2-07',
    world: 2,
    type: 'fix',
    title: 'Finance Mix Mix-up',
    giver: 'walt',
    story: "I wanted deals by store AND finance type, but DuckDB yells at me about GROUP BY.",
    question: 'Fix the query so it returns location_id, finance_type and deals (count) for every combination.',
    concepts: ['GROUP BY', 'multiple columns'],
    starter: 'SELECT location_id, finance_type, COUNT(*) AS deals\nFROM deals\nGROUP BY location_id',
    solution: 'SELECT location_id, finance_type, COUNT(*) AS deals FROM deals GROUP BY location_id, finance_type',
    expectedColumns: ['location_id', 'finance_type', 'deals'],
    hints: [
      'Every non-aggregated column in SELECT must be in GROUP BY.',
      'finance_type is in SELECT but not in GROUP BY.',
      'GROUP BY location_id, finance_type (or GROUP BY ALL)',
    ],
    why: "If SQL let you skip it, which finance_type would it show for a store that has three? That's why the rule exists. DuckDB and Snowflake both support GROUP BY ALL as a shortcut.",
  },
  {
    id: 'w2-08',
    world: 2,
    type: 'read',
    title: 'The Show Report',
    giver: 'tony',
    story: 'The marketing agency sent this query with their RV Show recap. What does it actually tell us?',
    question: 'Which question does this query answer?',
    concepts: ['GROUP BY multiple columns', 'HAVING'],
    query:
      "SELECT location_id, rv_class_interest, COUNT(*) AS leads\nFROM leads\nWHERE source = 'RV Show'\nGROUP BY location_id, rv_class_interest\nHAVING COUNT(*) >= 20\nORDER BY leads DESC",
    choices: [
      'Which stores got at least 20 leads from RV shows in total?',
      'For each store, which RV classes got 20+ RV-show leads, and how many?',
      'Which RV classes got 20+ leads across all sources?',
      'The top 20 store/class combinations from RV shows.',
    ],
    answer: 1,
    explanations: [
      'Close, but the groups are store AND class, so a store with 30 RV-show leads spread over 4 classes might not appear at all.',
      'Yes. WHERE keeps RV-show leads, GROUP BY makes one group per (store, class), and HAVING keeps groups with 20+.',
      "The WHERE clause keeps only source = 'RV Show'.",
      'HAVING >= 20 is a threshold on the count, not a LIMIT of 20 rows.',
    ],
    hints: ['Read FROM → WHERE → GROUP BY → HAVING.', 'What is one group here?', 'HAVING is a threshold on each (store, class) group.'],
    why: 'Travel trailers dominate show leads, which is useful when deciding which units to haul to the next show.',
  },
  {
    id: 'w2-09',
    world: 2,
    type: 'predict',
    title: 'The Missing Months',
    giver: 'marge',
    story: 'I asked for cash deals by store and month. Before you run it: how many rows?',
    question: 'Predict the number of rows (there are 12 stores and 24 months of history).',
    concepts: ['GROUP BY', 'empty groups'],
    query:
      "SELECT location_id,\n       DATE_TRUNC('month', deal_date) AS month,\n       COUNT(*) AS cash_deals\nFROM deals\nWHERE deal_status = 'Funded'\n  AND finance_type = 'Cash'\nGROUP BY 1, 2",
    measure: 'rows',
    decoys: [
      { sql: 'SELECT 12 * 24', why: '12 × 24 assumes every store sold a cash deal every month. Groups with zero rows simply do not exist in GROUP BY output.' },
      { sql: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded' AND finance_type = 'Cash'", why: 'That is the number of cash deals (rows before grouping), not the number of groups.' },
      { sql: 'SELECT 24', why: 'That would be one row per month, but we also group by store.' },
    ],
    explanation: 'Only (store, month) pairs that actually had a funded cash deal become groups. Months with zero cash deals are missing entirely.',
    hints: ['Can GROUP BY create a group for data that does not exist?', 'Some small stores go months without a cash deal.', 'It is less than 12 × 24.'],
    why: 'Missing zero-rows break charts and month-over-month math. To show zeros you need a calendar table (or generate_series) LEFT JOINed to your data. HR & People Ops uses that trick.',
  },
  {
    id: 'w2-10',
    world: 2,
    type: 'stakeholder',
    title: 'Why Are Sales Down?',
    giver: 'tony',
    story: 'Tony just saw the June DMS report and he is spiraling.',
    vague: "Why are sales down?! The June report looks terrible. I need to know what's going on before Rhonda sees it.",
    question: 'Figure out what Tony actually needs, investigate, and brief him.',
    concepts: ['clarifying questions', 'COUNT_IF', 'Stakeholder Mode'],
    clarify: [
      { text: 'Down compared to what: last month, or the same month last year?', good: true, reply: 'Same month last year. June versus last June. RVs are seasonal, so that is the fair comparison.' },
      { text: 'Is the report counting funded deals, or everything we signed?', good: true, reply: 'Uh... I think the DMS report only counts funded deals. Does that matter?' },
      { text: 'Should I build a dashboard with 40 charts first?', good: false, reply: 'I need an answer by lunch, not a dashboard.' },
      { text: 'Can you send me the whole database export?', good: false, reply: "...You already have the database. That's why you're here." },
      { text: 'Is this for the whole group or one store?', good: true, reply: 'The whole group.' },
    ],
    investigate: {
      question: 'Compare June 2025 with June 2026: return yr, funded (funded deals), pending (pending deals) and signed (all deals that were not unwound), one row per year.',
      solution:
        "SELECT YEAR(deal_date) AS yr, COUNT_IF(deal_status = 'Funded') AS funded, COUNT_IF(deal_status = 'Pending') AS pending, COUNT_IF(deal_status <> 'Unwound') AS signed FROM deals WHERE MONTH(deal_date) = 6 AND YEAR(deal_date) IN (2025, 2026) GROUP BY yr ORDER BY yr",
      orderMatters: true,
      expectedColumns: ['yr', 'funded', 'pending', 'signed'],
      hints: [
        'YEAR(deal_date) and MONTH(deal_date) pull parts out of a date.',
        "Use three COUNT_IFs: deal_status = 'Funded', = 'Pending', and <> 'Unwound'.",
        "SELECT YEAR(deal_date) AS yr, COUNT_IF(deal_status = 'Funded') AS funded, COUNT_IF(deal_status = 'Pending') AS pending, COUNT_IF(deal_status <> 'Unwound') AS signed FROM deals WHERE MONTH(deal_date) = 6 AND YEAR(deal_date) IN (2025, 2026) GROUP BY yr ORDER BY yr",
      ],
    },
    present: {
      facts: {
        signed26: "SELECT COUNT(*) FROM deals WHERE deal_status <> 'Unwound' AND deal_date BETWEEN DATE '2026-06-01' AND DATE '2026-06-30'",
        signed25: "SELECT COUNT(*) FROM deals WHERE deal_status <> 'Unwound' AND deal_date BETWEEN DATE '2025-06-01' AND DATE '2025-06-30'",
        funded26: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded' AND deal_date BETWEEN DATE '2026-06-01' AND DATE '2026-06-30'",
        funded25: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded' AND deal_date BETWEEN DATE '2025-06-01' AND DATE '2025-06-30'",
        pending26: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Pending' AND deal_date BETWEEN DATE '2026-06-01' AND DATE '2026-06-30'",
        droppct: "SELECT 100.0 * (1 - COUNT_IF(deal_date >= DATE '2026-06-01') / COUNT_IF(deal_date < DATE '2026-01-01')) FROM deals WHERE deal_status = 'Funded' AND MONTH(deal_date) = 6",
      },
      cards: [
        { id: 'a', role: 'answer', text: "Sales aren't really down: we signed {signed26} deals this June versus {signed25} last June.", note: 'The answer card goes first: lead with the direct answer.' },
        { id: 's', role: 'sowhat', text: "The dip is funding timing: {pending26} June deals are still pending with lenders, so let's push F&I to get them funded before month-end.", note: 'The so-what explains why it matters and what to do. It goes second.' },
        { id: 'd', role: 'detail', text: 'Funded-only, June shows {funded26} vs {funded25}, which looks like a {droppct:%} drop until those contracts fund.', note: 'The supporting detail goes last.' },
        { id: 'x1', role: 'distractor', text: 'Sales are down {droppct:%}! We should cut prices on everything immediately.', note: "That uses funded deals only (pending ones are missing) and jumps to a costly conclusion. Check the metric's definition first." },
        { id: 'x2', role: 'distractor', text: 'I ran eleven queries and learned a lot about the deals table.', note: "Process isn't an answer. Stakeholders want the conclusion, not the journey." },
        { id: 'x3', role: 'distractor', text: "Here's a spreadsheet with every June deal and all 19 columns.", note: "Don't bring a table, bring an answer." },
      ],
    },
    hints: ['Ask what "down" is compared to.', 'Funded vs pending matters a lot at month-end.', 'Answer → So-what → Detail.'],
    why: "Half of analytics is figuring out the real question. \"Sales are down\" turned out to be \"funded deals lag at month-end\", and a price cut would have been an expensive mistake. Clarify first, define the metric, then answer in three sentences.",
    codex: ['funded'],
  },

  // ---- bosses ------------------------------------------------------------------
  {
    id: 'w2-mb-1',
    world: 2,
    type: 'fix',
    bossOnly: true,
    title: 'Wraith 1',
    giver: 'tony',
    story: 'The Wraith hid an aggregate in the WHERE clause!',
    question: 'Fix it: salespeople (salesperson_id) whose average front_gross is above 8000, with that average (avg_front).',
    concepts: ['HAVING'],
    starter: 'SELECT salesperson_id, AVG(front_gross) AS avg_front\nFROM deals\nWHERE AVG(front_gross) > 8000\nGROUP BY salesperson_id',
    solution: 'SELECT salesperson_id, AVG(front_gross) AS avg_front FROM deals GROUP BY salesperson_id HAVING AVG(front_gross) > 8000',
    hints: ['Aggregates cannot be filtered in WHERE.', 'Use HAVING after GROUP BY.', '… GROUP BY salesperson_id HAVING AVG(front_gross) > 8000'],
    why: 'HAVING filters groups.',
  },
  {
    id: 'w2-mb-2',
    world: 2,
    type: 'write',
    bossOnly: true,
    title: 'Wraith 2',
    giver: 'tony',
    story: 'Quick: which stores have more than 850 leads?',
    question: 'Return location_id and leads (count) for stores with more than 850 leads.',
    concepts: ['HAVING'],
    solution: 'SELECT location_id, COUNT(*) AS leads FROM leads GROUP BY location_id HAVING COUNT(*) > 850',
    hints: ['Group by store.', 'Filter the groups with HAVING.', 'SELECT location_id, COUNT(*) AS leads FROM leads GROUP BY location_id HAVING COUNT(*) > 850'],
    why: 'Threshold reports are everywhere in dealerships.',
  },
  {
    id: 'w2-mb-3',
    world: 2,
    type: 'read',
    bossOnly: true,
    title: 'Wraith 3',
    giver: 'tony',
    story: 'The Wraith asks a riddle.',
    question: 'In this query, which clause removes rows BEFORE any grouping happens?',
    concepts: ['logical order'],
    query: "SELECT source, COUNT(*) AS n\nFROM leads\nWHERE status <> 'Lost'\nGROUP BY source\nHAVING COUNT(*) > 100\nORDER BY n DESC",
    choices: ['HAVING', 'WHERE', 'ORDER BY', 'SELECT'],
    answer: 1,
    explanations: ['HAVING runs after grouping.', 'Correct: WHERE runs right after FROM, before GROUP BY.', 'ORDER BY only sorts, near the very end.', 'SELECT runs after grouping and HAVING.'],
    hints: ['FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY', 'Which one is before GROUP BY?', 'WHERE'],
    why: 'Logical order is the key to reading SQL.',
  },
  {
    id: 'w2-b-1',
    world: 2,
    type: 'write',
    bossOnly: true,
    title: 'Funnel 1',
    giver: 'tony',
    story: 'The Stalled Funnel is leaking leads! Count them by stage.',
    question: 'Return status and leads (count) for every lead status.',
    concepts: ['GROUP BY'],
    solution: 'SELECT status, COUNT(*) AS leads FROM leads GROUP BY status',
    hints: ['Group by status.', 'COUNT(*)', 'SELECT status, COUNT(*) AS leads FROM leads GROUP BY status'],
    why: 'The funnel view shows where leads get stuck.',
  },
  {
    id: 'w2-b-2',
    world: 2,
    type: 'write',
    bossOnly: true,
    title: 'Funnel 2',
    giver: 'tony',
    story: 'Plug the leak: close rate by store!',
    question: "Return location_id and close_rate_pct (100 × leads with status 'Sold' ÷ all leads) for every store.",
    concepts: ['COUNT_IF'],
    solution: "SELECT location_id, 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM leads GROUP BY location_id",
    hints: ['COUNT_IF for sold.', 'Divide by COUNT(*), times 100.0.', "SELECT location_id, 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM leads GROUP BY location_id"],
    why: 'Close rate by store shows which sales teams convert.',
  },
  {
    id: 'w2-b-3',
    world: 2,
    type: 'predict',
    bossOnly: true,
    title: 'Funnel 3',
    giver: 'tony',
    story: 'Final blow: predict it!',
    question: 'How many rows will this return?',
    concepts: ['HAVING'],
    query: "SELECT source\nFROM leads\nGROUP BY source\nHAVING 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) > 10",
    measure: 'rows',
    decoys: [
      { sql: 'SELECT 6', why: 'That is every source. Some close below 10%.' },
      { sql: 'SELECT 1', why: 'More than one source closes above 10%.' },
      { sql: 'SELECT 5', why: 'Website and third-party marketplace leads both close below 10%.' },
    ],
    explanation: 'Referral, walk-in, RV show and phone leads close above 10%; website and marketplace leads do not.',
    hints: ['Remember the close-rate table from terminal 5.', 'Which sources beat 10%?', 'Four of them.'],
    why: 'Remembering rough magnitudes of your business metrics makes you faster and catches bugs.',
  },
];

export const WORLD_2: World = {
  id: 2,
  name: 'Sales Floor',
  building: 'showroom',
  giver: 'tony',
  tagline: 'GROUP BY, HAVING, COUNT/SUM/AVG, date functions',
  concepts: ['GROUP BY', 'HAVING', 'COUNT', 'SUM', 'AVG', 'COUNT_IF', 'DATE_TRUNC'],
  lesson: [
    {
      title: 'Deals, gross and funding',
      body: 'Every retail sale is a row in `deals`. Front-end gross is the profit on the RV itself. A deal is Pending until the lender pays (funds) it, and an Unwound deal was reversed. Scoreboards usually count funded deals, so watch the deal_status filter!',
    },
    {
      title: 'Leads and the funnel',
      body: 'The CRM tracks leads through stages: New → Working → Appointment Set → Sold (or Lost). Close rate = sold leads ÷ all leads. Lead source tells marketing where the money works.',
    },
    {
      title: 'GROUP BY in one picture',
      body: 'GROUP BY squashes many rows into one row per group. Every SELECT column must be either a group key or an aggregate (COUNT, SUM, AVG, MIN, MAX). WHERE filters rows before grouping; HAVING filters groups after.',
      sql: "SELECT location_id, COUNT(*) AS units   -- one row per store\nFROM deals\nWHERE deal_status = 'Funded'           -- rows first\nGROUP BY location_id\nHAVING COUNT(*) > 100                  -- then groups",
    },
  ],
  challenges: ['w2-01', 'w2-02', 'w2-03', 'w2-04', 'w2-05', 'w2-06', 'w2-07', 'w2-08', 'w2-09', 'w2-10'],
  miniBoss: {
    id: 'w2-mini',
    name: 'The WHERE/HAVING Wraith',
    sprite: 'wraith',
    mini: true,
    intro: 'A chill fills the showroom. Filters are firing in the wrong order, and aggregates are showing up where they do not belong!',
    victory: 'The Wraith dissolves into a neat pile of HAVING clauses.',
    timer: 120,
    phases: [{ name: 'Wrong Order', taunt: 'WHERE or HAVING? You will never know!', questions: ['w2-mb-1', 'w2-mb-2', 'w2-mb-3'] }],
  },
  boss: {
    id: 'w2-boss',
    name: 'The Stalled Funnel',
    sprite: 'funnel',
    mini: false,
    intro: 'A giant leaky funnel blocks the showroom door. Leads pour in the top and drip out the bottom, lost forever!',
    victory: 'The funnel clogs, then pops. Every lead lands neatly in the CRM. Tony does a victory lap.',
    timer: 150,
    phases: [
      { name: 'Leak Check', taunt: 'Where do my leads go? Nobody knows!', questions: ['w2-b-1'] },
      { name: 'Conversion Chaos', taunt: 'Close rate? What close rate?', questions: ['w2-b-2'] },
      { name: 'Final Squeeze', taunt: 'Guess! GUESS!', questions: ['w2-b-3'] },
    ],
  },
};
