import type { Challenge, World } from '../types';

const WO_JOIN = 'JOIN wo_jobs j ON j.wo_number = w.wo_number AND j.location_id = w.location_id';

export const W3_CHALLENGES: Challenge[] = [
  {
    id: 'w3-01',
    world: 3,
    type: 'write',
    title: 'A/C Season',
    giver: 'priya',
    story: 'Summer means roof A/C repairs. Pull every CP-AC job with the name of the store that did it.',
    question: "Return job_id, wo_number, location_name and flag_hours for jobs with job_code 'CP-AC'.",
    concepts: ['INNER JOIN', 'table aliases'],
    starter: 'SELECT j.job_id, j.wo_number, l.location_name, j.flag_hours\nFROM wo_jobs j\nJOIN locations l ON ',
    solution: "SELECT j.job_id, j.wo_number, l.location_name, j.flag_hours FROM wo_jobs j JOIN locations l ON l.location_id = j.location_id WHERE j.job_code = 'CP-AC'",
    expectedColumns: ['job_id', 'wo_number', 'location_name', 'flag_hours'],
    hints: [
      'A JOIN glues rows from two tables together where a condition matches.',
      'Match the store: ON l.location_id = j.location_id',
      "…FROM wo_jobs j JOIN locations l ON l.location_id = j.location_id WHERE j.job_code = 'CP-AC'",
    ],
    why: 'Joins turn IDs into names people understand. The alias (j, l) keeps long queries readable; you will see them in every real report.',
    codex: ['work-order'],
  },
  {
    id: 'w3-02',
    world: 3,
    type: 'fix',
    title: "Earl's Warning",
    giver: 'earl',
    story: 'Some genius built a jobs-by-bill-type report and it says we did NINETY THOUSAND customer-pay jobs. We did not.',
    question: 'Fix the join so each job is counted once: return bill_type and jobs.',
    concepts: ['composite key', 'fan-out'],
    starter: 'SELECT w.bill_type, COUNT(*) AS jobs\nFROM work_orders w\nJOIN wo_jobs j ON j.wo_number = w.wo_number\nGROUP BY w.bill_type',
    solution: `SELECT w.bill_type, COUNT(*) AS jobs FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type`,
    expectedColumns: ['bill_type', 'jobs'],
    hints: [
      'Every store has its own work order #10001. How does the join know which store?',
      'A work order is unique by (wo_number, location_id): a composite key.',
      'ON j.wo_number = w.wo_number AND j.location_id = w.location_id',
    ],
    why: 'Joining on half of a composite key matched every job to the same WO number at all 12 stores, a 10× fan-out. X-Ray shows the row count exploding at the JOIN step. Always check what makes a row unique.',
    codex: ['composite-key', 'fan-out'],
  },
  {
    id: 'w3-03',
    world: 3,
    type: 'write',
    title: 'Who Pays for the Work?',
    giver: 'priya',
    story: 'I need labor sales split by bill type: how much is customer pay, warranty and internal?',
    question: 'Return bill_type and labor_sales (sum of flag_hours × labor_rate), biggest first.',
    concepts: ['JOIN', 'SUM', 'composite key'],
    solution: `SELECT w.bill_type, SUM(j.flag_hours * j.labor_rate) AS labor_sales FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type ORDER BY labor_sales DESC`,
    orderMatters: true,
    expectedColumns: ['bill_type', 'labor_sales'],
    hints: [
      'bill_type lives on the work order header, and hours and rate live on the jobs.',
      'Join on BOTH wo_number and location_id.',
      `SELECT w.bill_type, SUM(j.flag_hours * j.labor_rate) AS labor_sales FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type ORDER BY labor_sales DESC`,
    ],
    why: 'Customer pay is the most profitable labor. Warranty pays lower manufacturer rates and internal work (PDI and recon) is the dealer paying itself. Service managers watch the mix constantly.',
    codex: ['bill-types', 'flag-hours'],
  },
  {
    id: 'w3-04',
    world: 3,
    type: 'write',
    title: 'Tech Efficiency',
    giver: 'earl',
    story: "Go on, look up my efficiency. I dare you. Then look up everybody else's.",
    question: 'Return technician (first_name || \' \' || last_name), flag_hours, actual_hours and efficiency_pct (100 × flag ÷ actual) per technician, most efficient first.',
    concepts: ['JOIN', 'string concatenation', 'ratios'],
    solution:
      "SELECT e.first_name || ' ' || e.last_name AS technician, SUM(j.flag_hours) AS flag_hours, SUM(j.actual_hours) AS actual_hours, 100 * SUM(j.flag_hours) / SUM(j.actual_hours) AS efficiency_pct FROM wo_jobs j JOIN employees e ON e.employee_id = j.technician_id GROUP BY technician ORDER BY efficiency_pct DESC",
    orderMatters: true,
    expectedColumns: ['technician', 'flag_hours', 'actual_hours', 'efficiency_pct'],
    hints: [
      'technician_id on wo_jobs points at employees.employee_id.',
      "|| glues strings together: e.first_name || ' ' || e.last_name",
      'Divide the SUMS, not the average of per-job ratios: 100 * SUM(flag_hours) / SUM(actual_hours).',
    ],
    why: 'Earl flags 1.6 hours for every hour on the clock. Efficiency drives shop capacity and flat-rate pay. Note: ratio of sums ≠ average of ratios, and the ratio of sums is the correct way to measure efficiency.',
    codex: ['tech-efficiency'],
  },
  {
    id: 'w3-05',
    world: 3,
    type: 'write',
    title: 'Effective Labor Rate',
    giver: 'priya',
    story: 'Our door rate is posted on the wall, but what do we REALLY earn per hour once warranty and internal work drag it down?',
    question: 'Return location_name and effective_labor_rate (labor sales ÷ flag hours) per store, highest first.',
    concepts: ['JOIN', 'weighted average'],
    solution:
      'SELECT l.location_name, SUM(j.flag_hours * j.labor_rate) / SUM(j.flag_hours) AS effective_labor_rate FROM wo_jobs j JOIN locations l ON l.location_id = j.location_id GROUP BY l.location_name ORDER BY effective_labor_rate DESC',
    orderMatters: true,
    expectedColumns: ['location_name', 'effective_labor_rate'],
    hints: [
      'ELR = total labor dollars ÷ total hours billed.',
      'AVG(labor_rate) would weight a 0.5-hour job like a 10-hour job. Use SUM ÷ SUM.',
      'SUM(j.flag_hours * j.labor_rate) / SUM(j.flag_hours)',
    ],
    why: 'Effective labor rate is always below the door rate because warranty and internal work pay less. Managers use it to price, negotiate warranty rates, and spot excessive discounting.',
    codex: ['elr'],
  },
  {
    id: 'w3-06',
    world: 3,
    type: 'write',
    title: 'Parts Gross',
    giver: 'priya',
    story: 'Parts is the quiet money-maker. Show me parts gross by bill type.',
    question: 'Return bill_type and parts_gross (sum of parts_sale − parts_cost), biggest first.',
    concepts: ['JOIN', 'SUM'],
    solution: `SELECT w.bill_type, SUM(j.parts_sale - j.parts_cost) AS parts_gross FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type ORDER BY parts_gross DESC`,
    orderMatters: true,
    expectedColumns: ['bill_type', 'parts_gross'],
    hints: ['Same composite-key join as before.', 'SUM(parts_sale - parts_cost)', `…FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type`],
    why: 'Internal parts are sold at cost (≈ $0 gross) and warranty at a small markup. Customer-pay parts carry the margin, which is why fixed-ops directors chase CP work.',
    codex: ['parts-gross'],
  },
  {
    id: 'w3-07',
    world: 3,
    type: 'write',
    title: 'Skipped the PDI?',
    giver: 'priya',
    story: 'Every new unit is supposed to get a PDI before it sells. Find new, in-stock units that have NO internal work order at all.',
    question: "Return stock_no and received_date for units with condition 'New' and status 'In Stock' that have no Internal work order.",
    concepts: ['anti-join', 'NOT EXISTS', 'LEFT JOIN … IS NULL'],
    solution:
      "SELECT u.stock_no, u.received_date FROM units u WHERE u.condition = 'New' AND u.status = 'In Stock' AND NOT EXISTS (SELECT 1 FROM work_orders w WHERE w.stock_no = u.stock_no AND w.bill_type = 'Internal')",
    expectedColumns: ['stock_no', 'received_date'],
    hints: [
      'You want units where a match does NOT exist: an anti-join.',
      "Option A: LEFT JOIN work_orders w ON w.stock_no = u.stock_no AND w.bill_type = 'Internal' … WHERE w.wo_number IS NULL",
      "Option B: WHERE NOT EXISTS (SELECT 1 FROM work_orders w WHERE w.stock_no = u.stock_no AND w.bill_type = 'Internal')",
    ],
    why: 'These are old units received before our service history starts, plus a few with broken received dates. A missing PDI is a customer-experience risk and a warranty headache. DuckDB also has a literal ANTI JOIN keyword.',
    codex: ['pdi'],
  },
  {
    id: 'w3-08',
    world: 3,
    type: 'write',
    title: 'Recon Drift',
    giver: 'marge',
    story: "Accounting says some used units have $0 recon, but service swears they reconditioned them. If that's true, our front gross is overstated.",
    question:
      "For used units whose recon_cost is 0 or NULL, return stock_no and wo_recon: the total internal work-order cost (flag_hours × labor_rate + parts_sale). Only units that have internal WO cost. Biggest first.",
    concepts: ['JOIN', 'COALESCE', 'composite key', 'data quality'],
    solution:
      "SELECT u.stock_no, SUM(j.flag_hours * j.labor_rate + j.parts_sale) AS wo_recon FROM units u JOIN work_orders w ON w.stock_no = u.stock_no AND w.bill_type = 'Internal' JOIN wo_jobs j ON j.wo_number = w.wo_number AND j.location_id = w.location_id WHERE u.condition = 'Used' AND COALESCE(u.recon_cost, 0) = 0 GROUP BY u.stock_no ORDER BY wo_recon DESC",
    orderMatters: true,
    expectedColumns: ['stock_no', 'wo_recon'],
    hints: [
      'Three tables: units → work_orders (Internal) → wo_jobs.',
      'COALESCE(recon_cost, 0) = 0 catches both NULL and 0.',
      'Group by stock_no and SUM the job costs.',
    ],
    why: "These 120 units had real recon work that never posted to the unit. Their front gross is overstated by the recon amount. That's a real, common DMS problem, and a great thing to flag to the controller.",
    codex: ['recon'],
  },
  {
    id: 'w3-09',
    world: 3,
    type: 'read',
    title: 'The Sneaky LEFT JOIN',
    giver: 'devin',
    story: 'Someone wanted "every unit, with its warranty work orders if it has any". This is what they wrote.',
    question: 'What does this query actually return?',
    concepts: ['LEFT JOIN', 'WHERE on the right table'],
    query: "SELECT u.stock_no, w.wo_number\nFROM units u\nLEFT JOIN work_orders w ON w.stock_no = u.stock_no\nWHERE w.bill_type = 'Warranty'",
    choices: [
      'Every unit, with warranty work orders where they exist (NULL otherwise)',
      'Only units that have at least one warranty work order',
      'Only units with NO warranty work orders',
      'An error: you cannot use WHERE with a LEFT JOIN',
    ],
    answer: 1,
    explanations: [
      "That's what they wanted, but the WHERE runs after the join and throws away the NULL rows.",
      "Right. Unmatched units get w.bill_type = NULL, and NULL = 'Warranty' is not true, so WHERE removes them. The LEFT JOIN silently became an INNER JOIN. Fix: move the condition into ON.",
      "It's the opposite: units without a match are removed.",
      'WHERE after a LEFT JOIN is perfectly legal, which is why this bug is sneaky.',
    ],
    hints: ['What is w.bill_type for a unit with no matching work order?', 'Is NULL = \'Warranty\' true?', 'Filters on the right table belong in ON if you want to keep unmatched rows.'],
    why: 'This bug is everywhere in real reports. Rule of thumb: in a LEFT JOIN, conditions about the right-hand table go in the ON clause.',
  },
  {
    id: 'w3-10',
    world: 3,
    type: 'predict',
    title: 'LEFT JOIN Row Count',
    giver: 'devin',
    story: 'Here is the corrected version. Before you run it: how many rows?',
    question: 'Predict the row count. (There are 1,565 units.)',
    concepts: ['LEFT JOIN', 'fan-out'],
    query: "SELECT u.stock_no, w.wo_number\nFROM units u\nLEFT JOIN work_orders w\n  ON w.stock_no = u.stock_no\n AND w.bill_type = 'Warranty'",
    measure: 'rows',
    decoys: [
      { sql: 'SELECT COUNT(*) FROM units', why: 'A LEFT JOIN keeps every unit, but units with 2 warranty visits appear twice (fan-out).' },
      { sql: "SELECT COUNT(*) FROM work_orders WHERE bill_type = 'Warranty'", why: 'That is the inner-join count, which drops units without warranty work.' },
      { sql: "SELECT COUNT(DISTINCT stock_no) FROM work_orders WHERE bill_type = 'Warranty'", why: 'That counts units that had warranty work, not result rows.' },
    ],
    explanation: 'Every unit appears at least once (LEFT JOIN), and units with several warranty work orders appear once per work order.',
    hints: ['LEFT JOIN never drops left-side rows.', 'Can one unit match more than one warranty WO?', 'A bit more than the number of units.'],
    why: 'Knowing that LEFT JOIN = "at least one row per left row, more if it fans out" lets you sanity-check any join instantly.',
  },

  // ---- bosses
  {
    id: 'w3-mb-1',
    world: 3,
    type: 'write',
    bossOnly: true,
    title: 'Crab 1',
    giver: 'earl',
    story: 'The Composite Key Crab pinches one key at a time. Use both!',
    question: 'Return location_id and jobs: the number of job lines per store that match a work order header.',
    concepts: ['composite key'],
    solution: `SELECT w.location_id, COUNT(*) AS jobs FROM work_orders w ${WO_JOIN} GROUP BY w.location_id`,
    hints: ['Join both key columns.', 'Group by w.location_id.', `SELECT w.location_id, COUNT(*) AS jobs FROM work_orders w ${WO_JOIN} GROUP BY w.location_id`],
    why: 'Composite keys everywhere in DMS data.',
  },
  {
    id: 'w3-mb-2',
    world: 3,
    type: 'read',
    bossOnly: true,
    title: 'Crab 2',
    giver: 'earl',
    story: 'Which join is correct?',
    question: 'Which ON clause correctly joins wo_jobs (j) to work_orders (w)?',
    concepts: ['composite key'],
    query: '-- work_orders PRIMARY KEY (wo_number, location_id)\n-- wo_jobs has wo_number and location_id',
    choices: ['ON j.wo_number = w.wo_number', 'ON j.location_id = w.location_id', 'ON j.wo_number = w.wo_number AND j.location_id = w.location_id', 'ON j.job_id = w.wo_number'],
    answer: 2,
    explanations: ['Matches across all stores: fan-out.', 'Matches every job to every WO at the same store: massive fan-out.', 'Correct: both parts of the key.', 'job_id is a different thing entirely.'],
    hints: ['What makes a work order unique?', 'Two columns.', 'Both of them in the ON.'],
    why: 'Always join on the full key.',
  },
  {
    id: 'w3-mb-3',
    world: 3,
    type: 'fix',
    bossOnly: true,
    title: 'Crab 3',
    giver: 'earl',
    story: 'Final pinch: fix it!',
    question: 'Fix the query: total flag_hours per bill_type.',
    concepts: ['composite key'],
    starter: 'SELECT w.bill_type, SUM(j.flag_hours) AS flag_hours\nFROM work_orders w\nJOIN wo_jobs j ON j.wo_number = w.wo_number\nGROUP BY w.bill_type',
    solution: `SELECT w.bill_type, SUM(j.flag_hours) AS flag_hours FROM work_orders w ${WO_JOIN} GROUP BY w.bill_type`,
    hints: ['Missing half the key.', 'Add location_id.', 'AND j.location_id = w.location_id'],
    why: 'Same bug, different metric. It inflates everything.',
  },
  {
    id: 'w3-b-1',
    world: 3,
    type: 'fix',
    bossOnly: true,
    title: 'Phantom 1',
    giver: 'priya',
    story: 'The Fan-Out Phantom is counting jobs as work orders!',
    question: 'Fix it: count WORK ORDERS (not job lines) per bill_type. Return bill_type and work_orders.',
    concepts: ['COUNT DISTINCT', 'fan-out'],
    starter: `SELECT w.bill_type, COUNT(*) AS work_orders\nFROM work_orders w\n${WO_JOIN}\nGROUP BY w.bill_type`,
    solution: 'SELECT bill_type, COUNT(*) AS work_orders FROM work_orders GROUP BY bill_type',
    hints: ['Do you even need the jobs table?', 'Count the headers, one row per work order.', 'SELECT bill_type, COUNT(*) AS work_orders FROM work_orders GROUP BY bill_type'],
    why: 'Joining to a child table multiplies parent rows. Count at the right grain (or use COUNT(DISTINCT …)).',
  },
  {
    id: 'w3-b-2',
    world: 3,
    type: 'predict',
    bossOnly: true,
    title: 'Phantom 2',
    giver: 'priya',
    story: 'The Phantom clones itself. How many clones?',
    question: 'How many rows does this return?',
    concepts: ['fan-out'],
    query: 'SELECT *\nFROM work_orders w\nJOIN wo_jobs j ON j.wo_number = w.wo_number',
    measure: 'rows',
    decoys: [
      { sql: 'SELECT COUNT(*) FROM wo_jobs', why: 'That would be true with the full composite key. Without it, every job matches the same WO number at every store.' },
      { sql: 'SELECT COUNT(*) FROM work_orders', why: 'Joining to jobs creates at least one row per job, not per WO.' },
      { sql: 'SELECT COUNT(*) FROM wo_jobs j JOIN work_orders w USING (wo_number, location_id)', why: 'That is the correct join, not this one.' },
    ],
    explanation: 'Each job matches every work order with the same number across stores, roughly 10× too many rows.',
    hints: ['WO 10001 exists at all 12 stores.', 'Each job matches ~10 headers.', 'Over 100,000.'],
    why: 'Fan-out math: rows multiply by the number of matches.',
  },
  {
    id: 'w3-b-3',
    world: 3,
    type: 'write',
    bossOnly: true,
    title: 'Phantom 3',
    giver: 'priya',
    story: 'Banish it with a clean, correct report!',
    question: 'Return location_id and parts_gross (sum of parts_sale − parts_cost) for Customer Pay work only, joined correctly.',
    concepts: ['composite key', 'JOIN'],
    solution: `SELECT w.location_id, SUM(j.parts_sale - j.parts_cost) AS parts_gross FROM work_orders w ${WO_JOIN} WHERE w.bill_type = 'Customer Pay' GROUP BY w.location_id`,
    hints: ['Composite join.', "Filter bill_type = 'Customer Pay'.", 'Group by w.location_id.'],
    why: 'Clean joins = trustworthy numbers.',
  },
];

export const WORLD_3: World = {
  id: 3,
  name: 'Service Bay',
  building: 'service',
  giver: 'priya',
  tagline: 'JOINs: inner, left, anti-joins, composite keys',
  concepts: ['INNER JOIN', 'LEFT JOIN', 'anti-join', 'composite keys', 'fan-out'],
  lesson: [
    {
      title: 'Work orders (ROs)',
      body: 'Every RV that comes into service gets a work order (a.k.a. repair order, RO). The header (work_orders) says who pays: Customer Pay, Warranty (the manufacturer) or Internal (the dealer: PDI and recon). The job lines (wo_jobs) hold the labor and parts.',
    },
    {
      title: 'Flat rate, flag hours and efficiency',
      body: 'Techs are paid by the job, from a labor guide: a job "flags" 2.0 hours whether it takes 1.5 or 3. Efficiency = flag hours ÷ actual hours. Effective labor rate = labor dollars ÷ hours billed.',
    },
    {
      title: 'Composite keys and fan-out',
      body: 'WO numbers restart at every store: each store has an RO #10001. So a work order is unique by (wo_number, location_id). Join on BOTH, or every job matches 12 headers and your totals explode (fan-out).',
      sql: 'SELECT w.bill_type, SUM(j.flag_hours)\nFROM work_orders w\nJOIN wo_jobs j\n  ON j.wo_number   = w.wo_number\n AND j.location_id = w.location_id   -- the part people forget\nGROUP BY w.bill_type',
    },
  ],
  challenges: ['w3-01', 'w3-02', 'w3-03', 'w3-04', 'w3-05', 'w3-06', 'w3-07', 'w3-08', 'w3-09', 'w3-10'],
  miniBoss: {
    id: 'w3-mini',
    name: 'The Composite Key Crab',
    sprite: 'crab',
    mini: true,
    intro: 'Click-clack! A crab with a key in each claw scuttles out from under Lift 2. It only ever uses ONE claw at a time...',
    victory: 'Both claws snap shut on the right keys, and the crab scuttles away to join things properly elsewhere.',
    timer: 120,
    phases: [{ name: 'Pinch', taunt: 'One key is plenty! Click-clack!', questions: ['w3-mb-1', 'w3-mb-2', 'w3-mb-3'] }],
  },
  boss: {
    id: 'w3-boss',
    name: 'The Fan-Out Phantom',
    sprite: 'phantom',
    mini: false,
    intro: 'The lights flicker. Every total in the service report doubles, then triples. The Fan-Out Phantom has possessed the joins!',
    victory: 'The clones collapse back into one. Totals return to normal, and Earl mutters "about time".',
    timer: 150,
    phases: [
      { name: 'Miscount', taunt: 'Jobs, work orders, what is the difference?', questions: ['w3-b-1'] },
      { name: 'Clone Army', taunt: 'Count my clones! You cannot!', questions: ['w3-b-2'] },
      { name: 'Last Haunt', taunt: 'Your parts gross is MINE!', questions: ['w3-b-3'] },
    ],
  },
};
