import type { Challenge, World } from '../types';

const BACK = '(SELECT deal_id, SUM(sale_price - cost) AS back_gross FROM fi_products GROUP BY deal_id)';

export const W4_CHALLENGES: Challenge[] = [
  {
    id: 'w4-01',
    world: 4,
    type: 'write',
    title: 'Cash or Financed?',
    giver: 'walt',
    story: 'I only care about two buckets: did the customer pay cash, or did somebody finance it? Label them and count them.',
    question: "For funded deals, return pay_method ('Cash' when finance_type is 'Cash', otherwise 'Financed') and deals (count).",
    concepts: ['CASE WHEN', 'GROUP BY'],
    starter: "SELECT CASE WHEN finance_type = 'Cash' THEN 'Cash' ELSE 'Financed' END AS pay_method,\n       COUNT(*) AS deals\nFROM deals\n",
    solution: "SELECT CASE WHEN finance_type = 'Cash' THEN 'Cash' ELSE 'Financed' END AS pay_method, COUNT(*) AS deals FROM deals WHERE deal_status = 'Funded' GROUP BY pay_method",
    expectedColumns: ['pay_method', 'deals'],
    hints: ["CASE WHEN condition THEN value ELSE other END builds a new column.", 'You can GROUP BY the CASE alias.', "…WHERE deal_status = 'Funded' GROUP BY pay_method"],
    why: 'Financed deals are where F&I earns: finance reserve plus products like GAP. The cash vs financed mix is the first number any F&I director asks about.',
    codex: ['fi'],
    snowflake: [{ title: 'Inline IF', snowflake: "IFF(finance_type = 'Cash', 'Cash', 'Financed')", duckdb: "CASE WHEN finance_type = 'Cash' THEN 'Cash' ELSE 'Financed' END", note: 'Snowflake has IFF(); DuckDB has IF(). CASE works in both.' }],
  },
  {
    id: 'w4-02',
    world: 4,
    type: 'write',
    title: 'Back-End Gross',
    giver: 'walt',
    story: 'Front-end gross is the RV. Back-end gross is MY department: the products. Show me the ten richest deals by back-end gross.',
    question: 'Return deal_id and back_gross (sum of sale_price − cost from fi_products) for the top 10 deals.',
    concepts: ['SUM', 'GROUP BY', 'LIMIT'],
    solution: 'SELECT deal_id, SUM(sale_price - cost) AS back_gross FROM fi_products GROUP BY deal_id ORDER BY back_gross DESC LIMIT 10',
    orderMatters: true,
    expectedColumns: ['deal_id', 'back_gross'],
    hints: ['Each product row has its own profit: sale_price − cost.', 'Add them up per deal.', 'SELECT deal_id, SUM(sale_price - cost) AS back_gross FROM fi_products GROUP BY deal_id ORDER BY back_gross DESC LIMIT 10'],
    why: 'In RV retail, a well-sold service contract can out-earn the unit itself. Back-end gross is why F&I managers are among the best-paid people in a dealership.',
    codex: ['back-gross'],
  },
  {
    id: 'w4-03',
    world: 4,
    type: 'write',
    title: 'Back-End by Store',
    giver: 'walt',
    story: 'Now roll it up: total back-end gross per store, funded deals only.',
    question: "Return location_id and back_gross (sum of product sale_price − cost) for funded deals, biggest first.",
    concepts: ['JOIN', 'SUM'],
    solution: "SELECT d.location_id, SUM(p.sale_price - p.cost) AS back_gross FROM deals d JOIN fi_products p ON p.deal_id = d.deal_id WHERE d.deal_status = 'Funded' GROUP BY d.location_id ORDER BY back_gross DESC",
    orderMatters: true,
    expectedColumns: ['location_id', 'back_gross'],
    hints: ['Store and status live on deals; profit lives on fi_products.', 'JOIN on deal_id.', "…FROM deals d JOIN fi_products p ON p.deal_id = d.deal_id WHERE d.deal_status = 'Funded' GROUP BY d.location_id"],
    why: 'Totals favor big stores. To compare fairly you need a per-unit number, which is what PVR does next.',
  },
  {
    id: 'w4-04',
    world: 4,
    type: 'write',
    title: 'PVR',
    giver: 'walt',
    story: "Per Vehicle Retailed. The number I'm judged by. For every store: units, total PVR (front + back) and F&I PVR (back only).",
    question:
      'For funded deals, return location_name, units, total_pvr ((front_gross + back_gross) ÷ units) and fi_pvr (back_gross ÷ units), highest fi_pvr first. Deals with no products count as $0 back-end.',
    concepts: ['subquery in FROM', 'LEFT JOIN', 'COALESCE', 'PVR'],
    solution: `SELECT l.location_name, COUNT(*) AS units, SUM(d.front_gross + COALESCE(b.back_gross, 0)) / COUNT(*) AS total_pvr, SUM(COALESCE(b.back_gross, 0)) / COUNT(*) AS fi_pvr FROM deals d JOIN locations l ON l.location_id = d.location_id LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id WHERE d.deal_status = 'Funded' GROUP BY l.location_name ORDER BY fi_pvr DESC`,
    orderMatters: true,
    expectedColumns: ['location_name', 'units', 'total_pvr', 'fi_pvr'],
    hints: [
      'First total the products per deal in a subquery, so each deal has ONE back_gross row (no fan-out).',
      'LEFT JOIN that subquery to deals, because a deal with no products still counts as a unit.',
      `…LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id … SUM(COALESCE(b.back_gross, 0)) / COUNT(*)`,
    ],
    why: 'PVR divides by retail units, so wholesales and unwinds must be excluded. The pre-aggregate-then-join pattern is the standard cure for fan-out. Look at the bottom of the list: one store is way behind.',
    codex: ['pvr'],
  },
  {
    id: 'w4-05',
    world: 4,
    type: 'write',
    title: 'Service Contract Penetration',
    giver: 'walt',
    story: 'Every customer must be offered every product. Penetration tells me who actually buys. Start with Extended Service Contracts.',
    question: "For funded deals, return location_id and esc_penetration_pct: 100 × (deals with an 'Extended Service Contract') ÷ (all funded deals).",
    concepts: ['LEFT JOIN', 'conditional count', 'penetration'],
    solution:
      "SELECT d.location_id, 100.0 * COUNT(p.deal_id) / COUNT(*) AS esc_penetration_pct FROM deals d LEFT JOIN fi_products p ON p.deal_id = d.deal_id AND p.product = 'Extended Service Contract' WHERE d.deal_status = 'Funded' GROUP BY d.location_id",
    expectedColumns: ['location_id', 'esc_penetration_pct'],
    hints: [
      'LEFT JOIN the ESC product rows only (put the product filter in the ON clause!).',
      'COUNT(p.deal_id) counts only matched rows; COUNT(*) counts all deals.',
      "…LEFT JOIN fi_products p ON p.deal_id = d.deal_id AND p.product = 'Extended Service Contract' … 100.0 * COUNT(p.deal_id) / COUNT(*)",
    ],
    why: 'COUNT(column) skips NULLs, which is exactly what you want after a LEFT JOIN. Putting the product filter in WHERE would drop every deal without an ESC and give you 100%.',
    codex: ['penetration'],
  },
  {
    id: 'w4-06',
    world: 4,
    type: 'write',
    title: 'Finance Mix, One Row per Store',
    giver: 'walt',
    story: 'I want the finance mix as a wide table: one row per store with cash, retail finance and outside finance counts side by side.',
    question: 'For funded deals, return location_id, deals, cash, retail_finance and outside_finance counts, ordered by location_id.',
    concepts: ['conditional aggregation', 'SUM(CASE…)'],
    solution:
      "SELECT location_id, COUNT(*) AS deals, SUM(CASE WHEN finance_type = 'Cash' THEN 1 ELSE 0 END) AS cash, SUM(CASE WHEN finance_type = 'Retail Finance' THEN 1 ELSE 0 END) AS retail_finance, SUM(CASE WHEN finance_type = 'Outside Finance' THEN 1 ELSE 0 END) AS outside_finance FROM deals WHERE deal_status = 'Funded' GROUP BY location_id ORDER BY location_id",
    orderMatters: true,
    expectedColumns: ['location_id', 'deals', 'cash', 'retail_finance', 'outside_finance'],
    hints: ['SUM(CASE WHEN x THEN 1 ELSE 0 END) counts rows where x is true.', 'One CASE per column.', 'COUNT_IF(finance_type = \'Cash\') also works in DuckDB and Snowflake.'],
    why: '"Pivoting" with conditional aggregation is how most dealer scorecards are built. Outside Finance means the customer used their own bank, so F&I earns no reserve on those deals.',
  },
  {
    id: 'w4-07',
    world: 4,
    type: 'write',
    title: 'Over-Allowance Watch',
    giver: 'walt',
    story: 'Some salespeople "buy" deals by overpaying for trades. It comes right out of front gross. Who does it most?',
    question: 'For funded deals with a trade, return salesperson_id, trades (count) and avg_over_allowance (average trade_allowance − trade_acv) for salespeople with at least 5 trades, worst first.',
    concepts: ['AVG', 'HAVING', 'over-allowance'],
    solution:
      "SELECT salesperson_id, COUNT(*) AS trades, AVG(trade_allowance - trade_acv) AS avg_over_allowance FROM deals WHERE deal_status = 'Funded' AND trade_in_stock_no IS NOT NULL GROUP BY salesperson_id HAVING COUNT(*) >= 5 ORDER BY avg_over_allowance DESC, salesperson_id",
    orderMatters: true,
    expectedColumns: ['salesperson_id', 'trades', 'avg_over_allowance'],
    hints: ['Only deals with a trade: trade_in_stock_no IS NOT NULL.', 'HAVING COUNT(*) >= 5 filters out tiny samples.', 'ORDER BY the average DESC (break ties by salesperson_id).'],
    why: 'Over-allowance (allowance − ACV) is a hidden discount: the customer thinks they got a great trade price, but the dealer eats it in front gross. Managers coach reps who habitually over-allow.',
    codex: ['acv', 'over-allowance', 'trade-in'],
  },
  {
    id: 'w4-08',
    world: 4,
    type: 'fix',
    title: 'The Inflated Front',
    giver: 'marge',
    story: 'This front-gross-by-store report is way higher than the P&L. Someone joined the product table in.',
    question: 'Fix it: return location_id and front_gross (sum of front_gross) for funded deals.',
    concepts: ['fan-out', 'grain'],
    starter: "SELECT d.location_id, SUM(d.front_gross) AS front_gross\nFROM deals d\nJOIN fi_products p ON p.deal_id = d.deal_id\nWHERE d.deal_status = 'Funded'\nGROUP BY d.location_id",
    solution: "SELECT location_id, SUM(front_gross) AS front_gross FROM deals WHERE deal_status = 'Funded' GROUP BY location_id",
    expectedColumns: ['location_id', 'front_gross'],
    hints: ['A deal with 3 products appears 3 times after the join.', 'And a deal with 0 products disappears!', 'You do not need fi_products at all for front gross.'],
    why: 'Two bugs in one: fan-out (double counting) AND an inner join dropping deals without products. Always aggregate at the grain of the metric: front gross lives on the deal.',
    codex: ['fan-out'],
  },
  {
    id: 'w4-09',
    world: 4,
    type: 'read',
    title: 'The GAP Report',
    giver: 'walt',
    story: "My old F&I director's favorite report. What does gap_pct actually measure?",
    question: 'What does gap_pct measure?',
    concepts: ['CASE', 'NULLIF', 'subqueries'],
    query:
      "SELECT location_id,\n       COUNT(*) AS deals,\n       SUM(CASE WHEN finance_type = 'Retail Finance' THEN 1 ELSE 0 END) AS financed_here,\n       ROUND(100.0 * SUM(CASE WHEN finance_type = 'Retail Finance' AND has_gap THEN 1 ELSE 0 END)\n             / NULLIF(SUM(CASE WHEN finance_type = 'Retail Finance' THEN 1 ELSE 0 END), 0), 1) AS gap_pct\nFROM (\n  SELECT d.*,\n         EXISTS (SELECT 1 FROM fi_products p\n                 WHERE p.deal_id = d.deal_id AND p.product = 'GAP') AS has_gap\n  FROM deals d\n  WHERE d.deal_status = 'Funded'\n) x\nGROUP BY location_id",
    choices: [
      'The percent of ALL funded deals that bought GAP',
      'The percent of dealer-financed (Retail Finance) deals that bought GAP',
      "Each store's share of the company's GAP sales",
      'The profit margin on GAP contracts',
    ],
    answer: 1,
    explanations: [
      'The denominator only counts Retail Finance deals, not all deals.',
      'Yes: numerator = retail-financed deals with GAP; denominator = retail-financed deals. GAP only makes sense on a loan, so this is the fair penetration rate.',
      'Nothing compares against a company total.',
      'No cost or price columns are involved.',
    ],
    hints: ['Read the inner query first: what is has_gap?', 'Look at the denominator of gap_pct.', 'NULLIF(x, 0) avoids dividing by zero.'],
    why: 'Choosing the right denominator is half of every KPI definition. GAP penetration is measured against financed deals because cash buyers cannot buy GAP.',
    codex: ['penetration'],
  },
  {
    id: 'w4-10',
    world: 4,
    type: 'stakeholder',
    title: 'Is F&I Slipping at Tucson?',
    giver: 'walt',
    story: 'Walt got a worried text from the Tucson GM.',
    vague: "Tucson says F&I is 'slipping'. Is it? What's going on over there?",
    question: 'Clarify, investigate, and brief Walt.',
    concepts: ['PVR', 'penetration', 'Stakeholder Mode'],
    clarify: [
      { text: 'Slipping on which metric: F&I PVR, product penetration, or finance mix?', good: true, reply: "PVR is the headline, but if it's low I need to know WHY." },
      { text: 'Compared to what: the rest of the group, or Tucson last year?', good: true, reply: 'Versus the group. Tucson should be middle of the pack.' },
      { text: 'Should I include unwound deals?', good: true, reply: 'No. Funded deals only, like always.' },
      { text: 'Can we just fire the F&I manager?', good: false, reply: "Whoa. Let's look at the data before we look at people." },
      { text: 'Do you want me to rebuild the whole DMS?', good: false, reply: 'I want an answer this week.' },
    ],
    investigate: {
      question:
        "For funded deals, return location_id, fi_pvr (back-end gross per deal, $0 for no products) and esc_pct (percent of deals with an 'Extended Service Contract'), one row per store.",
      solution: `SELECT d.location_id, SUM(COALESCE(b.back_gross, 0)) / COUNT(*) AS fi_pvr, 100.0 * COUNT(e.deal_id) / COUNT(*) AS esc_pct FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id LEFT JOIN fi_products e ON e.deal_id = d.deal_id AND e.product = 'Extended Service Contract' WHERE d.deal_status = 'Funded' GROUP BY d.location_id`,
      expectedColumns: ['location_id', 'fi_pvr', 'esc_pct'],
      hints: [
        'Two LEFT JOINs: the per-deal back_gross subquery, and the ESC product rows.',
        'fi_pvr = SUM(COALESCE(back_gross, 0)) / COUNT(*); esc_pct = 100.0 * COUNT(e.deal_id) / COUNT(*).',
        `…FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id LEFT JOIN fi_products e ON e.deal_id = d.deal_id AND e.product = 'Extended Service Contract' WHERE d.deal_status = 'Funded' GROUP BY d.location_id`,
      ],
    },
    present: {
      facts: {
        tucson_pvr: `SELECT SUM(COALESCE(b.back_gross, 0)) / COUNT(*) FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id WHERE d.deal_status = 'Funded' AND d.location_id = 6`,
        group_pvr: `SELECT SUM(COALESCE(b.back_gross, 0)) / COUNT(*) FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id WHERE d.deal_status = 'Funded'`,
        tucson_esc: "SELECT 100.0 * COUNT(p.deal_id) / COUNT(*) FROM deals d LEFT JOIN fi_products p ON p.deal_id = d.deal_id AND p.product = 'Extended Service Contract' WHERE d.deal_status = 'Funded' AND d.location_id = 6",
        group_esc: "SELECT 100.0 * COUNT(p.deal_id) / COUNT(*) FROM deals d LEFT JOIN fi_products p ON p.deal_id = d.deal_id AND p.product = 'Extended Service Contract' WHERE d.deal_status = 'Funded'",
        tucson_fin: "SELECT 100.0 * COUNT_IF(finance_type = 'Retail Finance') / COUNT(*) FROM deals WHERE deal_status = 'Funded' AND location_id = 6",
      },
      cards: [
        { id: 'a', role: 'answer', text: "Yes. Tucson's F&I PVR is {tucson_pvr:$} per unit, less than half the group's {group_pvr:$}.", note: 'Lead with the answer: yes or no, plus the headline number.' },
        { id: 's', role: 'sowhat', text: 'The gap is product selling, not financing, so a menu-selling refresher for the Tucson F&I office is the fastest fix.', note: 'The so-what (what to do) goes second.' },
        { id: 'd', role: 'detail', text: 'Service-contract penetration is {tucson_esc:%} vs {group_esc:%} group-wide, while {tucson_fin:%} of their deals are dealer-financed (normal).', note: 'The supporting numbers go last.' },
        { id: 'x1', role: 'distractor', text: "Tucson's total back-end is lower because it's a smaller store.", note: "That's why we use PVR (per unit). Size doesn't explain a per-unit gap." },
        { id: 'x2', role: 'distractor', text: 'We should fire the Tucson F&I manager.', note: 'Recommending personnel action from one metric is not your call, and not a so-what the data supports.' },
        { id: 'x3', role: 'distractor', text: 'F&I is complicated and depends on many factors.', note: 'True but useless. No answer, no numbers.' },
      ],
    },
    hints: ['Clarify the metric and the comparison.', 'PVR and penetration together tell the story.', 'Answer → So-what → Detail.'],
    why: "Diagnosing *why* a KPI is off (products vs financing vs volume) turns a scary headline into a specific fix. Walt can act on 'menu-selling refresher'; he can't act on 'F&I is slipping'.",
    codex: ['pvr', 'penetration'],
  },

  // ---- bosses
  {
    id: 'w4-mb-1',
    world: 4,
    type: 'write',
    bossOnly: true,
    title: 'Ogre 1',
    giver: 'walt',
    story: 'The Over-Allowance Ogre is eating front gross!',
    question: 'Return the total over-allowance (sum of trade_allowance − trade_acv) across all funded deals with a trade, as total_over_allowance.',
    concepts: ['SUM'],
    solution: "SELECT SUM(trade_allowance - trade_acv) AS total_over_allowance FROM deals WHERE deal_status = 'Funded' AND trade_in_stock_no IS NOT NULL",
    hints: ['One number.', 'Filter to trades.', "SELECT SUM(trade_allowance - trade_acv) AS total_over_allowance FROM deals WHERE deal_status = 'Funded' AND trade_in_stock_no IS NOT NULL"],
    why: 'Total over-allowance is real money out of front gross.',
    codex: ['over-allowance'],
  },
  {
    id: 'w4-mb-2',
    world: 4,
    type: 'write',
    bossOnly: true,
    title: 'Ogre 2',
    giver: 'walt',
    story: 'Which store feeds the Ogre most?',
    question: 'Return location_id and avg_over_allowance (average allowance − ACV) for funded trade deals, highest first.',
    concepts: ['AVG'],
    solution: "SELECT location_id, AVG(trade_allowance - trade_acv) AS avg_over_allowance FROM deals WHERE deal_status = 'Funded' AND trade_in_stock_no IS NOT NULL GROUP BY location_id ORDER BY avg_over_allowance DESC",
    orderMatters: true,
    hints: ['Group by store.', 'AVG of the difference.', 'ORDER BY DESC'],
    why: 'Store-level patterns point at management habits.',
  },
  {
    id: 'w4-mb-3',
    world: 4,
    type: 'read',
    bossOnly: true,
    title: 'Ogre 3',
    giver: 'walt',
    story: 'The Ogre grunts a riddle.',
    question: 'A trade has ACV $20,000 and the customer was given an allowance of $22,500. What happens to front gross?',
    concepts: ['over-allowance'],
    query: '-- front_gross = sale_price − (invoice + recon) − (trade_allowance − trade_acv)',
    choices: ['It goes up by $2,500', 'It goes down by $2,500', 'No change', 'It goes down by $22,500'],
    answer: 1,
    explanations: ['Over-allowance is a cost, not income.', 'Right: $2,500 of over-allowance comes straight out of front gross.', 'The difference hits front gross.', 'Only the over-allowance, not the whole trade.'],
    hints: ['Allowance − ACV = ?', 'Is that a discount?', 'It reduces gross.'],
    why: 'Over-allowance is hidden discounting.',
  },
  {
    id: 'w4-b-1',
    world: 4,
    type: 'fix',
    bossOnly: true,
    title: 'Pirate 1',
    giver: 'walt',
    story: 'The PVR Pirate swapped the denominator!',
    question: 'Fix the F&I PVR for the whole group: back-end gross ÷ FUNDED DEALS (not ÷ products). Return fi_pvr.',
    concepts: ['PVR', 'grain'],
    starter: "SELECT SUM(p.sale_price - p.cost) / COUNT(*) AS fi_pvr\nFROM deals d\nJOIN fi_products p ON p.deal_id = d.deal_id\nWHERE d.deal_status = 'Funded'",
    solution: `SELECT SUM(COALESCE(b.back_gross, 0)) / COUNT(*) AS fi_pvr FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id WHERE d.deal_status = 'Funded'`,
    hints: ['COUNT(*) after joining products counts PRODUCTS.', 'Aggregate products per deal first, then LEFT JOIN.', `SELECT SUM(COALESCE(b.back_gross, 0)) / COUNT(*) AS fi_pvr FROM deals d LEFT JOIN ${BACK} b ON b.deal_id = d.deal_id WHERE d.deal_status = 'Funded'`],
    why: 'PVR is per VEHICLE, so divide by deals.',
  },
  {
    id: 'w4-b-2',
    world: 4,
    type: 'predict',
    bossOnly: true,
    title: 'Pirate 2',
    giver: 'walt',
    story: 'The Pirate hides deals without products. How many?',
    question: 'What number does this return?',
    concepts: ['LEFT JOIN', 'anti-join'],
    query: "SELECT COUNT(*)\nFROM deals d\nLEFT JOIN fi_products p ON p.deal_id = d.deal_id\nWHERE d.deal_status = 'Funded'\n  AND p.deal_id IS NULL",
    measure: 'value',
    decoys: [
      { sql: 'SELECT 0', why: 'Plenty of customers decline every product (especially cash buyers).' },
      { sql: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded'", why: 'That is all funded deals.' },
      { sql: "SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded' AND finance_type = 'Cash'", why: 'Many cash buyers skip products, but not all, and some financed buyers skip them too.' },
    ],
    explanation: 'LEFT JOIN + IS NULL is an anti-join: it counts funded deals with no F&I products at all.',
    hints: ['What does p.deal_id IS NULL mean after a LEFT JOIN?', 'Deals with zero products.', 'A few hundred.'],
    why: 'Zero-product deals are the biggest F&I opportunity.',
  },
  {
    id: 'w4-b-3',
    world: 4,
    type: 'write',
    bossOnly: true,
    title: 'Pirate 3',
    giver: 'walt',
    story: 'Take back the treasure: penetration for EVERY product!',
    question: "Return product and penetration_pct: 100 × (funded deals with that product) ÷ (all funded deals).",
    concepts: ['subquery', 'penetration'],
    solution: "SELECT p.product, 100.0 * COUNT(DISTINCT p.deal_id) / (SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded') AS penetration_pct FROM fi_products p JOIN deals d ON d.deal_id = p.deal_id WHERE d.deal_status = 'Funded' GROUP BY p.product",
    hints: ['A scalar subquery can provide the denominator.', 'COUNT(DISTINCT p.deal_id) per product.', "…/ (SELECT COUNT(*) FROM deals WHERE deal_status = 'Funded')"],
    why: 'The product penetration table is the F&I manager\'s report card.',
  },
];

export const WORLD_4: World = {
  id: 4,
  name: 'F&I Office',
  building: 'fi',
  giver: 'walt',
  tagline: 'CASE WHEN, conditional aggregation, calculated metrics',
  concepts: ['CASE WHEN', 'conditional aggregation', 'PVR', 'penetration', 'NULLIF'],
  lesson: [
    { title: 'The box', body: 'After a customer agrees on a price, they go to F&I (Finance & Insurance), a.k.a. "the box". The F&I manager arranges the loan and offers protection products: extended service contracts, GAP, tire & wheel, roadside and appearance protection.' },
    { title: 'Front vs back', body: "Front-end gross is profit on the RV (price − cost − over-allowance). Back-end gross is F&I profit: product sale price − product cost (and in real life, finance reserve). PVR = gross ÷ retail units, so stores of different sizes can be compared." },
    { title: 'CASE and conditional aggregation', body: 'CASE WHEN turns conditions into values. Wrap it in SUM or COUNT and you can count several categories side by side in one row, the classic "pivot".', sql: "SELECT location_id,\n  SUM(CASE WHEN finance_type = 'Cash' THEN 1 ELSE 0 END) AS cash,\n  COUNT_IF(finance_type = 'Retail Finance') AS financed\nFROM deals\nGROUP BY location_id" },
  ],
  challenges: ['w4-01', 'w4-02', 'w4-03', 'w4-04', 'w4-05', 'w4-06', 'w4-07', 'w4-08', 'w4-09', 'w4-10'],
  miniBoss: {
    id: 'w4-mini',
    name: 'The Over-Allowance Ogre',
    sprite: 'ogre',
    mini: true,
    intro: 'A hulking Ogre stomps out of the trade-appraisal lane, clutching a stack of overpaid trade-ins. "MORE ALLOWANCE!" it bellows.',
    victory: 'The Ogre shrinks down to ACV size and wanders off to the wholesale auction.',
    timer: 120,
    phases: [{ name: 'Trade Grab', taunt: 'Give them MORE for their trade!', questions: ['w4-mb-1', 'w4-mb-2', 'w4-mb-3'] }],
  },
  boss: {
    id: 'w4-boss',
    name: 'The PVR Pirate',
    sprite: 'pirate',
    mini: false,
    intro: 'Arr! A pirate has boarded the F&I office and is plundering back-end gross, miscounting every PVR on the way out!',
    victory: 'The Pirate walks the plank into a pile of correctly calculated PVRs. Walt straightens his tie approvingly.',
    timer: 160,
    phases: [
      { name: 'Wrong Denominator', taunt: 'Divide by products, divide by anything!', questions: ['w4-b-1'] },
      { name: 'Hidden Deals', taunt: 'Deals with no products? Never heard of them!', questions: ['w4-b-2'] },
      { name: 'Treasure Map', taunt: 'You will never map my penetration!', questions: ['w4-b-3'] },
    ],
  },
};
