import type { Challenge, World } from '../types';

const INSTOCK_AGE = "SELECT stock_no, location_id, as_of_date() - received_date AS days FROM units WHERE status = 'In Stock' AND received_date IS NOT NULL";
const INTEREST = 'f.funded_amount * f.interest_rate / 100 / 365 * (as_of_date() - f.funded_date)';

export const W5_CHALLENGES: Challenge[] = [
  {
    id: 'w5-01',
    world: 5,
    type: 'write',
    title: 'Days in Stock',
    giver: 'marge',
    story: "Every day a unit sits here costs me interest. Show me how long each in-stock unit has been on the lot, oldest first.",
    question: "For units with status 'In Stock' and a received_date, return stock_no, location_id and days_in_stock (as_of_date() − received_date), oldest first.",
    concepts: ['date math', 'as_of_date()', 'DATE_DIFF'],
    starter: "SELECT stock_no, location_id, as_of_date() - received_date AS days_in_stock\nFROM units\nWHERE ",
    solution: "SELECT stock_no, location_id, as_of_date() - received_date AS days_in_stock FROM units WHERE status = 'In Stock' AND received_date IS NOT NULL ORDER BY days_in_stock DESC",
    expectedColumns: ['stock_no', 'location_id', 'days_in_stock'],
    hints: [
      'Subtracting two DATEs in DuckDB gives the number of days.',
      "as_of_date() is the game's frozen \"today\" (2026-06-30). At work you'd use CURRENT_DATE.",
      "…WHERE status = 'In Stock' AND received_date IS NOT NULL ORDER BY days_in_stock DESC",
    ],
    why: 'Days in stock drives flooring interest, curtailments and pricing decisions. Aged units get discounted, wholesaled, or moved to another store.',
    codex: ['aging'],
    snowflake: [{ title: 'Days between dates', snowflake: 'DATEDIFF(day, received_date, CURRENT_DATE)', duckdb: "as_of_date() - received_date   -- or DATE_DIFF('day', received_date, as_of_date())" }],
  },
  {
    id: 'w5-02',
    world: 5,
    type: 'write',
    title: 'Aging Buckets',
    giver: 'marge',
    story: 'The lender wants aging in buckets: 0-90, 91-180, 181-270 and 270+ days. How many in-stock units in each?',
    question: "Return bucket ('0-90', '91-180', '181-270' or '270+') and units (count) for in-stock units with a received_date.",
    concepts: ['CASE WHEN', 'date math', 'aging'],
    solution: `SELECT CASE WHEN days <= 90 THEN '0-90' WHEN days <= 180 THEN '91-180' WHEN days <= 270 THEN '181-270' ELSE '270+' END AS bucket, COUNT(*) AS units FROM (${INSTOCK_AGE}) a GROUP BY bucket`,
    expectedColumns: ['bucket', 'units'],
    hints: [
      'Compute days first (a subquery helps), then CASE it into labels.',
      'CASE checks conditions in order, so WHEN days <= 90 … WHEN days <= 180 … works.',
      "CASE WHEN days <= 90 THEN '0-90' WHEN days <= 180 THEN '91-180' WHEN days <= 270 THEN '181-270' ELSE '270+' END",
    ],
    why: 'Aging buckets are on every floorplan audit and inventory meeting. The 181+ buckets are where curtailments bite, and 270+ units are prime wholesale candidates.',
    codex: ['aging', 'wholesale'],
  },
  {
    id: 'w5-03',
    world: 5,
    type: 'write',
    title: 'Aging by Store (CTE)',
    giver: 'marge',
    story: 'Which stores have the most stale inventory? Use a CTE so I can actually read the query next month.',
    question: 'Return location_name, units (in stock) and pct_over_180 (percent of those units older than 180 days) per store, worst first.',
    concepts: ['CTE', 'WITH', 'COUNT_IF'],
    starter: `WITH aged AS (\n  ${INSTOCK_AGE}\n)\nSELECT …`,
    solution: `WITH aged AS (${INSTOCK_AGE}) SELECT l.location_name, COUNT(*) AS units, 100.0 * COUNT_IF(a.days > 180) / COUNT(*) AS pct_over_180 FROM aged a JOIN locations l ON l.location_id = a.location_id GROUP BY l.location_name ORDER BY pct_over_180 DESC`,
    expectedColumns: ['location_name', 'units', 'pct_over_180'],
    hints: [
      'WITH name AS (query) defines a named temporary result you can SELECT from.',
      'COUNT_IF(days > 180) counts old units; divide by COUNT(*).',
      `WITH aged AS (${INSTOCK_AGE}) SELECT l.location_name, COUNT(*) AS units, 100.0 * COUNT_IF(a.days > 180) / COUNT(*) AS pct_over_180 FROM aged a JOIN locations l ON l.location_id = a.location_id GROUP BY l.location_name`,
    ],
    why: 'CTEs let you build a query in readable steps: "first compute ages, then summarize". X-Ray shows each CTE as its own step. Boise stands out, and the GM will want to know why.',
  },
  {
    id: 'w5-04',
    world: 5,
    type: 'write',
    title: 'Due Next 30 Days',
    giver: 'marge',
    story: "Cash planning: which curtailments come due in the next 30 days? I need to have the money ready.",
    question: 'Return curtailment_id, stock_no, due_date and amount_due for unpaid curtailments due after as_of_date() and within 30 days, soonest first.',
    concepts: ['date ranges', 'JOIN', 'curtailments'],
    solution: 'SELECT c.curtailment_id, f.stock_no, c.due_date, c.amount_due FROM curtailments c JOIN floorplan_loans f ON f.floorplan_id = c.floorplan_id WHERE c.paid_date IS NULL AND c.due_date > as_of_date() AND c.due_date <= as_of_date() + 30 ORDER BY c.due_date, c.curtailment_id',
    orderMatters: true,
    expectedColumns: ['curtailment_id', 'stock_no', 'due_date', 'amount_due'],
    hints: [
      'The stock_no is on floorplan_loans, so join on floorplan_id.',
      'as_of_date() + 30 is 30 days from "today".',
      'WHERE c.paid_date IS NULL AND c.due_date > as_of_date() AND c.due_date <= as_of_date() + 30',
    ],
    why: 'Curtailments are scheduled principal paydowns. Missing one can trigger lender penalties or an audit, so controllers forecast them weeks ahead.',
    codex: ['curtailment', 'floorplan'],
    snowflake: [{ title: 'Adding days', snowflake: 'DATEADD(day, 30, CURRENT_DATE)', duckdb: 'as_of_date() + 30   -- or + INTERVAL 30 DAY' }],
  },
  {
    id: 'w5-05',
    world: 5,
    type: 'write',
    title: 'Past Due',
    giver: 'marge',
    story: 'And the scary list: curtailments that are already past due and unpaid.',
    question: 'Return curtailment_id, stock_no, due_date, amount_due and days_late (as_of_date() − due_date) for unpaid curtailments due on or before as_of_date(), most late first.',
    concepts: ['date math', 'IS NULL'],
    solution: 'SELECT c.curtailment_id, f.stock_no, c.due_date, c.amount_due, as_of_date() - c.due_date AS days_late FROM curtailments c JOIN floorplan_loans f ON f.floorplan_id = c.floorplan_id WHERE c.paid_date IS NULL AND c.due_date <= as_of_date() ORDER BY days_late DESC, c.curtailment_id',
    orderMatters: true,
    expectedColumns: ['curtailment_id', 'stock_no', 'due_date', 'amount_due', 'days_late'],
    hints: ['Unpaid = paid_date IS NULL.', 'Past due = due_date <= as_of_date().', 'days_late = as_of_date() - c.due_date'],
    why: 'Late curtailments damage the lender relationship and can lead to higher rates or reduced credit lines.',
    codex: ['curtailment'],
  },
  {
    id: 'w5-06',
    world: 5,
    type: 'write',
    title: 'Flooring Interest',
    giver: 'marge',
    story: 'Show me the ten units that have cost us the most interest so far. I suspect some old Class A units are eating us alive.',
    question: 'For open loans (paid_off_date IS NULL), return stock_no and interest_to_date (funded_amount × interest_rate ÷ 100 ÷ 365 × days since funded_date), top 10.',
    concepts: ['date math', 'calculated columns'],
    solution: `SELECT f.stock_no, ${INTEREST} AS interest_to_date FROM floorplan_loans f WHERE f.paid_off_date IS NULL ORDER BY interest_to_date DESC LIMIT 10`,
    orderMatters: true,
    expectedColumns: ['stock_no', 'interest_to_date'],
    hints: ['interest_rate is a percent (7.75 means 7.75%), so divide by 100.', 'Daily interest = principal × rate ÷ 365.', `${INTEREST}`],
    why: "Simplified (it ignores curtailment paydowns), but the point stands: a $400k motorhome sitting 900+ days can burn $50k+ in interest. That's why aged units get aggressive pricing.",
    codex: ['flooring-interest'],
  },
  {
    id: 'w5-07',
    world: 5,
    type: 'write',
    title: 'About to Curtail',
    giver: 'marge',
    story: 'Which floored units will hit their FIRST curtailment (day 180) in the next month? If sales can move them now, we skip the paydown.',
    question: 'For open loans aged 150–179 days (as_of_date() − funded_date), return stock_no, loan_age_days and first_curtailment (10% of funded_amount), oldest first.',
    concepts: ['BETWEEN', 'date math'],
    solution: 'SELECT stock_no, as_of_date() - funded_date AS loan_age_days, funded_amount * 0.10 AS first_curtailment FROM floorplan_loans WHERE paid_off_date IS NULL AND as_of_date() - funded_date BETWEEN 150 AND 179 ORDER BY loan_age_days DESC, stock_no',
    orderMatters: true,
    expectedColumns: ['stock_no', 'loan_age_days', 'first_curtailment'],
    hints: ['Loan age counts from funded_date, not received_date.', 'BETWEEN 150 AND 179 (inclusive).', 'funded_amount * 0.10'],
    why: 'This "hot list" goes to the sales manager every week. A small discount now is cheaper than a 10% principal paydown next month.',
    codex: ['curtailment'],
  },
  {
    id: 'w5-08',
    world: 5,
    type: 'write',
    title: 'Above Their Store Average',
    giver: 'marge',
    story: 'Compare each open loan to its own store: which units have cost more interest than their store\'s average?',
    question: "Return stock_no, location_id and interest (interest to date) for open loans whose interest is above the average interest of open loans at the same store.",
    concepts: ['CTE', 'correlated subquery', 'window alternative'],
    solution: `WITH open_loans AS (SELECT f.stock_no, u.location_id, ${INTEREST} AS interest FROM floorplan_loans f JOIN units u ON u.stock_no = f.stock_no WHERE f.paid_off_date IS NULL) SELECT o.stock_no, o.location_id, o.interest FROM open_loans o WHERE o.interest > (SELECT AVG(o2.interest) FROM open_loans o2 WHERE o2.location_id = o.location_id)`,
    expectedColumns: ['stock_no', 'location_id', 'interest'],
    hints: [
      'Build open_loans (stock_no, location_id, interest) in a CTE; location_id comes from units.',
      'A correlated subquery can compute the average for the current row\'s store.',
      'WHERE o.interest > (SELECT AVG(o2.interest) FROM open_loans o2 WHERE o2.location_id = o.location_id)',
    ],
    why: 'Comparing to a peer group (same store) is fairer than a company-wide cutoff. You can also do this with AVG(interest) OVER (PARTITION BY location_id), which you will learn in Data Detective HQ.',
  },
  {
    id: 'w5-09',
    world: 5,
    type: 'read',
    title: 'The Correlated Riddle',
    giver: 'marge',
    story: "My predecessor loved correlated subqueries. I don't. What does this one return?",
    question: 'Which units does this query return?',
    concepts: ['correlated subquery'],
    query:
      "SELECT u.stock_no, u.location_id, u.msrp\nFROM units u\nWHERE u.status = 'In Stock'\n  AND u.msrp > (\n        SELECT AVG(u2.msrp)\n        FROM units u2\n        WHERE u2.location_id = u.location_id\n          AND u2.status = 'In Stock'\n      )",
    choices: [
      'In-stock units priced above the average in-stock MSRP of their own store',
      'In-stock units priced above the company-wide average MSRP',
      'The average MSRP of each store',
      'Units priced above the average of units that have already sold',
    ],
    answer: 0,
    explanations: [
      'Yes: the inner query re-runs for each outer row, using that row\'s location_id (u2.location_id = u.location_id).',
      'The inner WHERE ties it to the same store, so it is not company-wide.',
      'It returns units, not averages.',
      "The inner query filters status = 'In Stock', not sold units.",
    ],
    hints: ['Find where the inner query references the outer alias u.', 'The average is recomputed for each store.', 'Both queries filter In Stock.'],
    why: 'Correlated subqueries read like "for each row, look up something about its group". Window functions usually do the same job faster and more readably.',
  },
  {
    id: 'w5-10',
    world: 5,
    type: 'fix',
    title: 'Snowflake Paste',
    giver: 'devin',
    story: "I copied this from our Snowflake worksheet and DuckDB hates it. It should show when each upcoming curtailment's NEXT one would be due (90 days later).",
    question: 'Translate to DuckDB: return curtailment_id, due_date and next_due (due_date + 90 days) for unpaid curtailments due after as_of_date().',
    concepts: ['DATEADD', 'Snowflake ↔ DuckDB', 'intervals'],
    starter: 'SELECT curtailment_id, due_date, DATEADD(day, 90, due_date) AS next_due\nFROM curtailments\nWHERE paid_date IS NULL\n  AND due_date > as_of_date()',
    solution: 'SELECT curtailment_id, due_date, due_date + INTERVAL 90 DAY AS next_due FROM curtailments WHERE paid_date IS NULL AND due_date > as_of_date()',
    expectedColumns: ['curtailment_id', 'due_date', 'next_due'],
    hints: ['DuckDB has no DATEADD.', 'You can add an INTERVAL to a date.', 'due_date + INTERVAL 90 DAY (or due_date + 90)'],
    why: 'Most SQL is portable, but date functions differ between warehouses. Knowing the translation table (DATEADD ↔ + INTERVAL, DATEDIFF ↔ date − date, IFF ↔ CASE) saves hours.',
    snowflake: [{ title: 'Date arithmetic', snowflake: 'DATEADD(day, 90, due_date)\nDATEDIFF(day, a, b)', duckdb: "due_date + INTERVAL 90 DAY\nb - a   -- or DATE_DIFF('day', a, b)" }],
  },

  // ---- bosses
  {
    id: 'w5-mb-1',
    world: 5,
    type: 'write',
    bossOnly: true,
    title: 'Anaconda 1',
    giver: 'marge',
    story: 'The Aging Anaconda coils around the oldest units!',
    question: "Return the number of in-stock units older than 270 days as old_units.",
    concepts: ['date math'],
    solution: "SELECT COUNT(*) AS old_units FROM units WHERE status = 'In Stock' AND as_of_date() - received_date > 270",
    hints: ['One number.', 'as_of_date() - received_date > 270', "SELECT COUNT(*) AS old_units FROM units WHERE status = 'In Stock' AND as_of_date() - received_date > 270"],
    why: '270+ units are the wholesale candidates.',
  },
  {
    id: 'w5-mb-2',
    world: 5,
    type: 'write',
    bossOnly: true,
    title: 'Anaconda 2',
    giver: 'marge',
    story: 'Squeeze harder: average age by class!',
    question: "Return rv_class and avg_days (average days in stock) for in-stock units with a received_date.",
    concepts: ['AVG', 'date math'],
    solution: "SELECT rv_class, AVG(as_of_date() - received_date) AS avg_days FROM units WHERE status = 'In Stock' AND received_date IS NOT NULL GROUP BY rv_class",
    hints: ['Group by class.', 'AVG of the date difference.', "SELECT rv_class, AVG(as_of_date() - received_date) AS avg_days FROM units WHERE status = 'In Stock' AND received_date IS NOT NULL GROUP BY rv_class"],
    why: 'Class-level aging guides ordering: stop ordering what does not turn.',
  },
  {
    id: 'w5-mb-3',
    world: 5,
    type: 'predict',
    bossOnly: true,
    title: 'Anaconda 3',
    giver: 'marge',
    story: 'The Anaconda hisses a question.',
    question: 'How many rows does this return?',
    concepts: ['NULL', 'date math'],
    query: "SELECT stock_no\nFROM units\nWHERE status = 'In Stock'\n  AND as_of_date() - received_date <= 90",
    measure: 'rows',
    decoys: [
      { sql: "SELECT COUNT(*) FROM units WHERE status = 'In Stock'", why: 'That is every in-stock unit. The 90-day filter removes older ones.' },
      { sql: "SELECT COUNT(*) FROM units WHERE status = 'In Stock' AND (received_date IS NULL OR as_of_date() - received_date <= 90)", why: 'NULL received dates make the comparison NULL, so those rows are NOT kept.' },
      { sql: "SELECT COUNT(*) FROM units WHERE status = 'In Stock' AND as_of_date() - received_date > 90", why: 'That is the opposite filter.' },
    ],
    explanation: 'Only in-stock units received within the last 90 days. Units with a NULL received_date are silently dropped.',
    hints: ['What happens to NULL - date comparisons?', 'The 0-90 bucket.', 'Compare with the aging buckets.'],
    why: 'NULL dates silently disappear from date filters. Always check how many rows have NULLs.',
  },
  {
    id: 'w5-b-1',
    world: 5,
    type: 'write',
    bossOnly: true,
    title: 'Collector 1',
    giver: 'marge',
    story: 'The Curtailment Collector demands payment. How much is due in the next 60 days (plus anything past due)?',
    question: 'Return exposure: the sum of (amount_due − amount_paid) for unpaid curtailments due on or before as_of_date() + 60.',
    concepts: ['SUM', 'date math'],
    solution: 'SELECT SUM(amount_due - amount_paid) AS exposure FROM curtailments WHERE paid_date IS NULL AND due_date <= as_of_date() + 60',
    hints: ['Unpaid: paid_date IS NULL.', 'due_date <= as_of_date() + 60 includes past due.', 'SELECT SUM(amount_due - amount_paid) AS exposure FROM curtailments WHERE paid_date IS NULL AND due_date <= as_of_date() + 60'],
    why: 'Curtailment exposure is a cash-flow forecast line.',
  },
  {
    id: 'w5-b-2',
    world: 5,
    type: 'write',
    bossOnly: true,
    title: 'Collector 2',
    giver: 'marge',
    story: 'Which store owes the Collector the most?',
    question: 'Return location_name and exposure (same definition) by store, biggest first.',
    concepts: ['JOIN', 'SUM'],
    solution: 'SELECT l.location_name, SUM(c.amount_due - c.amount_paid) AS exposure FROM curtailments c JOIN floorplan_loans f ON f.floorplan_id = c.floorplan_id JOIN units u ON u.stock_no = f.stock_no JOIN locations l ON l.location_id = u.location_id WHERE c.paid_date IS NULL AND c.due_date <= as_of_date() + 60 GROUP BY l.location_name ORDER BY exposure DESC',
    orderMatters: true,
    hints: ['curtailments → floorplan_loans → units → locations.', 'Group by store name.', 'ORDER BY exposure DESC'],
    why: 'Exposure by store tells the GM where to push aged-unit sales.',
  },
  {
    id: 'w5-b-3',
    world: 5,
    type: 'write',
    bossOnly: true,
    title: 'Collector 3',
    giver: 'marge',
    story: 'Last trick: units SOLD but the loan is still open. The Collector calls that "sold out of trust"...',
    question: "Return stock_no and funded_amount for units with status 'Sold' whose floorplan loan has no paid_off_date.",
    concepts: ['JOIN', 'data quality'],
    solution: "SELECT f.stock_no, f.funded_amount FROM floorplan_loans f JOIN units u ON u.stock_no = f.stock_no WHERE u.status = 'Sold' AND f.paid_off_date IS NULL",
    hints: ['Join loans to units.', "u.status = 'Sold' AND f.paid_off_date IS NULL", "SELECT f.stock_no, f.funded_amount FROM floorplan_loans f JOIN units u ON u.stock_no = f.stock_no WHERE u.status = 'Sold' AND f.paid_off_date IS NULL"],
    why: "Most are pending deals or payoffs in flight, but a sold unit whose loan stays unpaid is 'sold out of trust', one of the most serious floorplan violations. Controllers check this list daily.",
  },
];

export const WORLD_5: World = {
  id: 5,
  name: 'Floorplan Vault',
  building: 'vault',
  giver: 'marge',
  tagline: 'Dates, CTEs, subqueries',
  concepts: ['date math', 'CTEs', 'subqueries', 'correlated subqueries', 'intervals'],
  lesson: [
    { title: 'Floorplan: the borrowed lot', body: "Dealers don't pay cash for new inventory. A floorplan lender pays the manufacturer, and the dealer pays interest every month until the unit sells, then pays the loan off. Interest starts on the funded date, which is often before the RV even arrives." },
    { title: 'Curtailments', body: "Lenders don't want to finance stale inventory forever. After 180 days they require a 10% principal paydown (a curtailment), then 5% every 90 days. Old units become cash drains." },
    { title: 'CTEs make long queries readable', body: 'A CTE (WITH name AS (...)) names a step. Build complex answers one step at a time, and X-Ray will show each step separately.', sql: "WITH aged AS (\n  SELECT stock_no, as_of_date() - received_date AS days\n  FROM units WHERE status = 'In Stock'\n)\nSELECT COUNT(*) FROM aged WHERE days > 180" },
  ],
  challenges: ['w5-01', 'w5-02', 'w5-03', 'w5-04', 'w5-05', 'w5-06', 'w5-07', 'w5-08', 'w5-09', 'w5-10'],
  miniBoss: {
    id: 'w5-mini',
    name: 'The Aging Anaconda',
    sprite: 'anaconda',
    mini: true,
    intro: 'Something long and slow slithers between the old units in back row. The Aging Anaconda grows one day longer every day!',
    victory: 'The Anaconda coils up and falls asleep on the wholesale truck. Good riddance.',
    timer: 120,
    phases: [{ name: 'The Squeeze', taunt: 'Every day I get longer. Hssss.', questions: ['w5-mb-1', 'w5-mb-2', 'w5-mb-3'] }],
  },
  boss: {
    id: 'w5-boss',
    name: 'The Curtailment Collector',
    sprite: 'collector',
    mini: false,
    intro: 'A figure in a pinstripe suit steps out of the vault, briefcase in hand. "Ten percent at 180 days. Five percent every ninety after. Pay up."',
    victory: 'The Collector checks the numbers twice, nods, and snaps the briefcase shut. "Everything is in order." He leaves quietly.',
    timer: 160,
    phases: [
      { name: 'The Bill', taunt: 'How much do you owe me? Do you even know?', questions: ['w5-b-1'] },
      { name: 'Store by Store', taunt: 'Which store shall I visit first?', questions: ['w5-b-2'] },
      { name: 'Out of Trust', taunt: 'Sold, but not paid off? Tsk tsk.', questions: ['w5-b-3'] },
    ],
  },
};
