import type { Challenge, World } from '../types';

const MONTHLY = "SELECT DATE_TRUNC('month', deal_date) AS month, COUNT(*) AS units FROM deals WHERE deal_status = 'Funded' GROUP BY 1";
const DEDUP = 'SELECT * FROM leads QUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1';

export const W6_CHALLENGES: Challenge[] = [
  {
    id: 'w6-01',
    world: 6,
    type: 'write',
    title: 'Seeing Double',
    giver: 'devin',
    story: 'After the March 2025 CRM migration, some leads showed up twice. lead_number is the business key, so it should be unique. Find the repeats.',
    question: 'Return lead_number and copies (how many rows share it) for every lead_number that appears more than once.',
    concepts: ['duplicate detection', 'GROUP BY', 'HAVING'],
    solution: 'SELECT lead_number, COUNT(*) AS copies FROM leads GROUP BY lead_number HAVING COUNT(*) > 1',
    expectedColumns: ['lead_number', 'copies'],
    hints: ['Group by the column that should be unique.', 'Keep groups with more than one row.', 'SELECT lead_number, COUNT(*) AS copies FROM leads GROUP BY lead_number HAVING COUNT(*) > 1'],
    why: 'GROUP BY key HAVING COUNT(*) > 1 is the universal duplicate detector. Run it on every table\'s business key when you meet new data.',
    codex: ['surrogate-key'],
  },
  {
    id: 'w6-02',
    world: 6,
    type: 'write',
    title: 'Number the Copies',
    giver: 'devin',
    story: "The migration re-inserted old leads with NEW lead_ids and stale statuses. The original is always the one with the LOWEST lead_id. Let's number each copy.",
    question: 'For duplicated lead_numbers only, return lead_id, lead_number, status and rn = ROW_NUMBER() within each lead_number ordered by lead_id.',
    concepts: ['ROW_NUMBER', 'window functions', 'PARTITION BY', 'duplicate'],
    solution:
      'SELECT lead_id, lead_number, status, ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) AS rn FROM leads WHERE lead_number IN (SELECT lead_number FROM leads GROUP BY lead_number HAVING COUNT(*) > 1)',
    expectedColumns: ['lead_id', 'lead_number', 'status', 'rn'],
    hints: [
      'ROW_NUMBER() OVER (PARTITION BY x ORDER BY y) numbers rows 1, 2, 3… within each x.',
      'Restrict to duplicated lead_numbers with WHERE lead_number IN (your query from terminal 1).',
      'ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) AS rn',
    ],
    why: 'Window functions add a column without collapsing rows, unlike GROUP BY. Look at the statuses: the rn = 2 copies are stale ("Working") while the originals say "Sold". Keeping the "latest" row by updated_at would keep the WRONG one. Understand the data before you dedupe!',
    codex: ['surrogate-key'],
  },
  {
    id: 'w6-03',
    world: 6,
    type: 'write',
    title: 'The Corrected Close Rate',
    giver: 'devin',
    story: 'Now dedupe for real (QUALIFY makes it one line) and recompute close rate by source.',
    question: "After keeping only the original row per lead_number, return source, leads, and close_rate_pct (100 × Sold ÷ leads).",
    concepts: ['QUALIFY', 'dedup', 'subquery'],
    solution: `SELECT source, COUNT(*) AS leads, 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM (${DEDUP}) d GROUP BY source`,
    expectedColumns: ['source', 'leads', 'close_rate_pct'],
    hints: [
      'QUALIFY filters on a window function, like HAVING does for aggregates.',
      'Dedupe in a subquery first: SELECT * FROM leads QUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1',
      "Then GROUP BY source over that subquery with COUNT_IF(status = 'Sold').",
    ],
    why: 'Duplicates inflate the denominator (leads) with stale non-sold copies, so close rate looks worse than it is. Compare with your Sales Floor numbers. QUALIFY exists in Snowflake too.',
    snowflake: [{ title: 'QUALIFY', snowflake: 'SELECT * FROM leads\nQUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1', duckdb: 'SELECT * FROM leads\nQUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1', note: 'Identical in both engines. In Postgres/SQL Server you need a subquery.' }],
  },
  {
    id: 'w6-04',
    world: 6,
    type: 'write',
    title: 'Mr. Negative One',
    giver: 'tony',
    story: 'Who is salesperson -1 and why do they have more deals than some of my people?!',
    question: 'Return unknown_deals (count) and unknown_front_gross (sum of front_gross) for deals whose salesperson_id is -1.',
    concepts: ['sentinel', '-1', 'data quality'],
    solution: 'SELECT COUNT(*) AS unknown_deals, SUM(front_gross) AS unknown_front_gross FROM deals WHERE salesperson_id = -1',
    expectedColumns: ['unknown_deals', 'unknown_front_gross'],
    hints: ['-1 is just a value; filter on it.', 'COUNT and SUM together.', 'SELECT COUNT(*) AS unknown_deals, SUM(front_gross) AS unknown_front_gross FROM deals WHERE salesperson_id = -1'],
    why: '-1 is a sentinel: a fake "unknown" key. It is not NULL, so IS NULL checks miss it, joins to employees silently drop it, and it shows up as a "person" in rankings. Convert with NULLIF(salesperson_id, -1) before joining or averaging.',
    codex: ['sentinel'],
  },
  {
    id: 'w6-05',
    world: 6,
    type: 'write',
    title: 'Orphaned Jobs',
    giver: 'devin',
    story: 'Some job lines point at work orders that no longer exist (someone purged headers). Find them.',
    question: 'Return job_id, wo_number and location_id for wo_jobs rows with no matching work_orders header (using both key columns).',
    concepts: ['orphans', 'anti-join', 'composite key'],
    solution: 'SELECT j.job_id, j.wo_number, j.location_id FROM wo_jobs j LEFT JOIN work_orders w ON w.wo_number = j.wo_number AND w.location_id = j.location_id WHERE w.wo_number IS NULL',
    expectedColumns: ['job_id', 'wo_number', 'location_id'],
    hints: ['Orphans = child rows with no parent: an anti-join.', 'LEFT JOIN the parent on the FULL key, keep rows where the parent is NULL.', '…WHERE w.wo_number IS NULL'],
    why: 'Orphans vanish from inner joins, so their dollars silently disappear from reports. Orphan checks (relationship tests) are a core data-quality test in dbt and every warehouse.',
  },
  {
    id: 'w6-06',
    world: 6,
    type: 'write',
    title: 'Running Total',
    giver: 'rhonda',
    story: 'I want year-to-date style momentum: units sold each month and the running total since the start of our data.',
    question: 'Return month, units and running_units (cumulative sum of units ordered by month), oldest first.',
    concepts: ['SUM() OVER', 'running total', 'window functions'],
    solution: `SELECT month, units, SUM(units) OVER (ORDER BY month) AS running_units FROM (${MONTHLY}) m ORDER BY month`,
    orderMatters: true,
    expectedColumns: ['month', 'units', 'running_units'],
    hints: [
      'First build monthly units (you did this on the Sales Floor) in a subquery or CTE.',
      'SUM(units) OVER (ORDER BY month) adds up everything up to the current row.',
      `SELECT month, units, SUM(units) OVER (ORDER BY month) AS running_units FROM (${MONTHLY}) m ORDER BY month`,
    ],
    why: 'Running totals power YTD reporting and burn-down charts. Note the window runs over the grouped result, which is why the subquery helps.',
  },
  {
    id: 'w6-07',
    world: 6,
    type: 'write',
    title: 'Top Gun per Store',
    giver: 'tony',
    story: 'Who is the #1 salesperson (by total front gross) at each store? Skip the -1 ghost.',
    question: "For funded deals with a real salesperson, return location_id, salesperson_id and front_gross (total) for the rank-1 salesperson at each store.",
    concepts: ['RANK', 'PARTITION BY', 'QUALIFY'],
    solution:
      "SELECT location_id, salesperson_id, SUM(front_gross) AS front_gross FROM deals WHERE deal_status = 'Funded' AND salesperson_id <> -1 GROUP BY location_id, salesperson_id QUALIFY RANK() OVER (PARTITION BY location_id ORDER BY SUM(front_gross) DESC) = 1",
    expectedColumns: ['location_id', 'salesperson_id', 'front_gross'],
    hints: [
      'Group by store and salesperson to get totals.',
      'RANK() OVER (PARTITION BY location_id ORDER BY SUM(front_gross) DESC) ranks within each store.',
      'QUALIFY RANK() OVER (…) = 1 keeps the winners.',
    ],
    why: 'RANK gives ties the same rank (1, 1, 3); ROW_NUMBER never ties; DENSE_RANK gives 1, 1, 2. Leaderboards usually want RANK.',
  },
  {
    id: 'w6-08',
    world: 6,
    type: 'write',
    title: 'Month over Month',
    giver: 'rhonda',
    story: 'For the ops review I need the change in units versus the prior month.',
    question: 'Return month, units and change (units − previous month\'s units), oldest first. The first month\'s change is NULL.',
    concepts: ['LAG', 'window functions'],
    solution: `SELECT month, units, units - LAG(units) OVER (ORDER BY month) AS change FROM (${MONTHLY}) m ORDER BY month`,
    orderMatters: true,
    expectedColumns: ['month', 'units', 'change'],
    hints: ['LAG(units) OVER (ORDER BY month) looks one row back.', 'The first month has no previous row, so LAG returns NULL.', `SELECT month, units, units - LAG(units) OVER (ORDER BY month) AS change FROM (${MONTHLY}) m ORDER BY month`],
    why: 'MoM and YoY deltas are in every management report. For seasonal businesses like RVs, compare to the same month last year with LAG(units, 12).',
  },
  {
    id: 'w6-09',
    world: 6,
    type: 'write',
    title: 'Share of the Pie',
    giver: 'rhonda',
    story: 'What share of the group\'s funded units does each store sell?',
    question: 'Return location_id, units and pct_of_total (100 × units ÷ total units across all stores).',
    concepts: ['SUM() OVER ()', 'percent of total'],
    solution: "SELECT location_id, COUNT(*) AS units, 100.0 * COUNT(*) / SUM(COUNT(*)) OVER () AS pct_of_total FROM deals WHERE deal_status = 'Funded' GROUP BY location_id",
    expectedColumns: ['location_id', 'units', 'pct_of_total'],
    hints: ['An empty OVER () means "over all rows of the result".', 'You can window an aggregate: SUM(COUNT(*)) OVER ()', "100.0 * COUNT(*) / SUM(COUNT(*)) OVER ()"],
    why: 'Percent-of-total without a second query or join is one of the most useful window tricks there is.',
  },
  {
    id: 'w6-10',
    world: 6,
    type: 'read',
    title: 'The Moving Average',
    giver: 'devin',
    story: 'Our old BI tool had this 3-month moving average. Read carefully.',
    question: 'For the FIRST month in the result, what is avg_3mo?',
    concepts: ['window frames', 'ROWS BETWEEN'],
    query: `WITH monthly AS (\n  ${MONTHLY}\n)\nSELECT month,\n       units,\n       AVG(units) OVER (ORDER BY month\n                        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS avg_3mo\nFROM monthly\nORDER BY month`,
    choices: ['NULL, because there are no previous months', "Exactly that month's units: the window only has one row", 'The average of the first three months', 'An error: the frame needs 3 rows'],
    answer: 1,
    explanations: [
      'AVG ignores missing rows. It does not return NULL just because the frame is short.',
      'Right. The frame is "up to 2 rows back", and there are none yet, so the average of one row is that row. The first two months are "partial" averages, which is worth labeling in a chart!',
      'That is the third month, the first one with a full frame.',
      'Short frames are allowed.',
    ],
    hints: ['ROWS BETWEEN 2 PRECEDING AND CURRENT ROW = up to 3 rows.', 'How many rows exist before the first month?', 'Average of one number = that number.'],
    why: 'Window frames decide which rows each calculation sees. Partial windows at the edges are a classic source of misleading charts.',
  },
  {
    id: 'w6-11',
    world: 6,
    type: 'stakeholder',
    title: 'The Close Rate Looks Too Low',
    giver: 'tony',
    story: 'Tony is convinced the CRM is lying about his team.',
    vague: "My close rate looks too low. The CRM is broken. Can you fix it?",
    question: 'Clarify, investigate the data, flag the problem to the right person, and brief Tony.',
    concepts: ['duplicate', 'QUALIFY', 'data quality', 'Stakeholder Mode'],
    clarify: [
      { text: 'Too low compared to what: last year, a benchmark, or your gut?', good: true, reply: "Compared to what my guys tell me. They say they close more than one in ten." },
      { text: 'Which close rate: all sources combined, for the whole group?', good: true, reply: 'Yeah, the overall number on the CRM dashboard.' },
      { text: 'When did it start looking wrong?', good: true, reply: 'Ever since... spring 2025? Around when IT switched CRMs.' },
      { text: 'Should I just change the number on the dashboard?', good: false, reply: "Tempting, but no. Rhonda would have my head. And yours." },
      { text: 'Do you want me to delete leads that look fake?', good: false, reply: "I don't know what's fake. That's why I asked you!" },
    ],
    investigate: {
      question: 'Return total_rows, unique_leads (distinct lead_number), raw_close_rate (100 × Sold ÷ all rows) and dedup_close_rate (same, after keeping the original row per lead_number) in one row.',
      solution: `SELECT (SELECT COUNT(*) FROM leads) AS total_rows, (SELECT COUNT(DISTINCT lead_number) FROM leads) AS unique_leads, (SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) FROM leads) AS raw_close_rate, (SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) FROM (${DEDUP}) d) AS dedup_close_rate`,
      expectedColumns: ['total_rows', 'unique_leads', 'raw_close_rate', 'dedup_close_rate'],
      hints: [
        'Scalar subqueries (SELECT …) can each produce one column.',
        'Dedup with QUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1.',
        `SELECT (SELECT COUNT(*) FROM leads) AS total_rows, (SELECT COUNT(DISTINCT lead_number) FROM leads) AS unique_leads, … (SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) FROM (${DEDUP}) d) AS dedup_close_rate`,
      ],
    },
    flag: {
      prompt: "Found something? Tell me what's wrong so I can fix it upstream.",
      options: [
        { text: '"The CRM is broken."', correct: false, reply: "Devin: \"...Broken how? I can't fix 'broken'.\" Be specific." },
        {
          text: '"~310 lead_numbers were duplicated by the March 2025 migration. The copies have newer lead_ids and stale statuses, which inflates lead counts and drags close rate down. Can we dedupe upstream, keeping the lowest lead_id?"',
          correct: true,
          reply: 'Devin: "Perfect bug report: what, where, impact, and a proposed fix. I\'ll add a uniqueness test on lead_number too."',
        },
        { text: 'Quietly delete the duplicate rows yourself in production.', correct: false, reply: 'Devin: "PLEASE never do that. Analysts flag; engineers fix at the source with tests."' },
      ],
    },
    present: {
      facts: {
        raw: "SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) FROM leads",
        dedup: `SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) FROM (${DEDUP}) d`,
        extra: 'SELECT COUNT(*) - COUNT(DISTINCT lead_number) FROM leads',
      },
      cards: [
        { id: 'a', role: 'answer', text: "The true close rate is {dedup:%}, not {raw:%}. The dashboard counts {extra} duplicate leads from the 2025 CRM migration.", note: 'Lead with the corrected number and the reason.' },
        { id: 's', role: 'sowhat', text: "Your team is doing slightly better than it looks. Devin is deduping the CRM at the source so the dashboard will be right going forward.", note: 'So-what: what it means and what happens next.' },
        { id: 'd', role: 'detail', text: 'The duplicates are stale copies (newer lead_id, old status), so they add leads that never "sell" and pull the rate down.', note: 'The mechanism is the supporting detail.' },
        { id: 'x1', role: 'distractor', text: 'The CRM is broken and nobody can trust any of it.', note: 'Overstated. One specific, fixable issue ≠ "nothing can be trusted".' },
        { id: 'x2', role: 'distractor', text: 'Close rate is actually 50% if we only count leads that got an appointment.', note: "Changing the definition to get a nicer number isn't an answer; it's spin." },
        { id: 'x3', role: 'distractor', text: 'I used ROW_NUMBER with PARTITION BY lead_number ORDER BY lead_id.', note: 'Tony does not need the SQL. Save it for Devin.' },
      ],
    },
    hints: ['Clarify the comparison and the timing.', 'Duplicates inflate the denominator.', 'Flag specifically: what, where, impact, fix.'],
    why: 'Flagging data issues early, specifically and to the right owner, is a superpower. It builds trust with engineers and saves stakeholders from bad decisions.',
    codex: ['crm', 'surrogate-key'],
  },

  // ---- bosses
  {
    id: 'w6-mb-1',
    world: 6,
    type: 'write',
    bossOnly: true,
    title: 'Specter 1',
    giver: 'devin',
    story: 'The Sentinel Specter haunts the leads table!',
    question: 'Return how many leads have assigned_employee_id = -1, as unknown_owner.',
    concepts: ['sentinel'],
    solution: 'SELECT COUNT(*) AS unknown_owner FROM leads WHERE assigned_employee_id = -1',
    hints: ['Filter on -1.', 'COUNT(*)', 'SELECT COUNT(*) AS unknown_owner FROM leads WHERE assigned_employee_id = -1'],
    why: 'Sentinels hide in every legacy table.',
    codex: ['sentinel'],
  },
  {
    id: 'w6-mb-2',
    world: 6,
    type: 'predict',
    bossOnly: true,
    title: 'Specter 2',
    giver: 'devin',
    story: 'The Specter giggles: "IS NULL will find me!" Will it?',
    question: 'What number does this return?',
    concepts: ['sentinel', 'NULL'],
    query: 'SELECT COUNT(*)\nFROM deals\nWHERE salesperson_id IS NULL',
    measure: 'value',
    decoys: [
      { sql: 'SELECT COUNT(*) FROM deals WHERE salesperson_id = -1', why: '-1 is not NULL! IS NULL finds nothing here.' },
      { sql: 'SELECT COUNT(*) FROM deals', why: 'Every deal has some salesperson_id value.' },
      { sql: 'SELECT 1', why: 'There are no NULL salesperson_ids at all.' },
    ],
    explanation: 'Zero. The unknowns are stored as -1, a real value, so IS NULL never matches.',
    hints: ['Is -1 NULL?', 'The unknowns are -1.', 'Zero.'],
    why: "Sentinels defeat NULL checks. That's exactly why they're dangerous.",
  },
  {
    id: 'w6-mb-3',
    world: 6,
    type: 'write',
    bossOnly: true,
    title: 'Specter 3',
    giver: 'devin',
    story: 'Banish it: turn -1 into a real NULL!',
    question: 'Return deal_id and salesperson_id with -1 converted to NULL (call it salesperson_id), for deals where salesperson_id = -1.',
    concepts: ['NULLIF'],
    solution: 'SELECT deal_id, NULLIF(salesperson_id, -1) AS salesperson_id FROM deals WHERE salesperson_id = -1',
    hints: ['NULLIF(a, b) returns NULL when a = b.', 'NULLIF(salesperson_id, -1)', 'SELECT deal_id, NULLIF(salesperson_id, -1) AS salesperson_id FROM deals WHERE salesperson_id = -1'],
    why: 'NULLIF is the standard sentinel cleaner.',
  },
  {
    id: 'w6-b-1',
    world: 6,
    type: 'write',
    bossOnly: true,
    title: 'Hydra 1',
    giver: 'devin',
    story: 'The Duplicate Lead Hydra rises! Count its heads.',
    question: 'Return extra_rows: total lead rows minus distinct lead_numbers.',
    concepts: ['COUNT DISTINCT'],
    solution: 'SELECT COUNT(*) - COUNT(DISTINCT lead_number) AS extra_rows FROM leads',
    hints: ['COUNT(*) vs COUNT(DISTINCT …).', 'Subtract.', 'SELECT COUNT(*) - COUNT(DISTINCT lead_number) AS extra_rows FROM leads'],
    why: 'Quick duplicate sizing.',
  },
  {
    id: 'w6-b-2',
    world: 6,
    type: 'fix',
    bossOnly: true,
    title: 'Hydra 2',
    giver: 'devin',
    story: 'It grows two heads for every wrong dedup! This one keeps the WRONG copy.',
    question: 'Fix the dedup so it keeps the ORIGINAL (lowest lead_id) row per lead_number. Return lead_id, lead_number, status.',
    concepts: ['ROW_NUMBER', 'QUALIFY', 'dedup'],
    starter: 'SELECT lead_id, lead_number, status\nFROM leads\nQUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY updated_at DESC) = 1',
    solution: 'SELECT lead_id, lead_number, status FROM leads QUALIFY ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) = 1',
    hints: ['The migration copies have NEWER updated_at timestamps.', 'The original has the lowest lead_id.', 'ORDER BY lead_id'],
    why: '"Keep the latest" is not always right. Know which copy is the truth.',
  },
  {
    id: 'w6-b-3',
    world: 6,
    type: 'write',
    bossOnly: true,
    title: 'Hydra 3',
    giver: 'devin',
    story: 'Cut the last head: the corrected close rate for the whole group!',
    question: 'Return close_rate_pct: 100 × Sold ÷ leads, after deduping (keep the lowest lead_id per lead_number).',
    concepts: ['QUALIFY', 'dedup'],
    solution: `SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM (${DEDUP}) d`,
    hints: ['Dedup in a subquery.', 'Then compute the rate.', `SELECT 100.0 * COUNT_IF(status = 'Sold') / COUNT(*) AS close_rate_pct FROM (${DEDUP}) d`],
    why: 'Clean data, true KPI.',
  },
  {
    id: 'w6-b-4',
    world: 6,
    type: 'write',
    bossOnly: true,
    title: 'Hydra 4',
    giver: 'devin',
    story: 'The Hydra regrows! Which month spawned the most duplicates?',
    question: 'Among migration copies (rows whose lead_number appeared earlier with a lower lead_id), return month (DATE_TRUNC of created_date) and copies, most first, top 1.',
    concepts: ['ROW_NUMBER', 'LIMIT'],
    solution: "SELECT DATE_TRUNC('month', created_date) AS month, COUNT(*) AS copies FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY lead_number ORDER BY lead_id) AS rn FROM leads) x WHERE rn > 1 GROUP BY 1 ORDER BY copies DESC, month LIMIT 1",
    orderMatters: true,
    hints: ['Copies are rows with rn > 1.', "Group by DATE_TRUNC('month', created_date).", 'ORDER BY copies DESC LIMIT 1'],
    why: 'Finding when duplicates were created points you at the root cause.',
  },
];

export const WORLD_6: World = {
  id: 6,
  name: 'Data Detective HQ',
  building: 'data',
  giver: 'devin',
  tagline: 'Window functions and data quality',
  concepts: ['ROW_NUMBER', 'RANK', 'LAG', 'SUM OVER', 'QUALIFY', 'duplicates', 'sentinels', 'orphans'],
  lesson: [
    { title: 'Messy data is normal', body: 'Real dealership data comes from several systems (DMS, CRM, floorplan portal) glued together by migrations and integrations. Expect duplicates, sentinel values like -1, orphan rows and NULL dates. Your job: detect, quantify, flag, then work around them.' },
    { title: 'Surrogate vs business keys', body: "lead_id is a surrogate key: the database invents it. lead_number is the business key people use. When a migration re-inserts a lead, it gets a new lead_id but keeps its lead_number, so one real lead becomes two rows." },
    { title: 'Window functions', body: 'A window function computes across related rows WITHOUT collapsing them. PARTITION BY = groups, ORDER BY = order inside each group, and the frame = which rows each calculation sees. QUALIFY filters on window results.', sql: 'SELECT lead_number, lead_id,\n       ROW_NUMBER() OVER (PARTITION BY lead_number\n                          ORDER BY lead_id) AS rn\nFROM leads\nQUALIFY rn = 1   -- keep the original' },
  ],
  challenges: ['w6-01', 'w6-02', 'w6-03', 'w6-04', 'w6-05', 'w6-06', 'w6-07', 'w6-08', 'w6-09', 'w6-10', 'w6-11'],
  miniBoss: {
    id: 'w6-mini',
    name: 'The Sentinel Specter',
    sprite: 'specter',
    mini: true,
    intro: 'A pale figure made entirely of -1s drifts through the server room. It is not NULL. It is not a person. It is... a sentinel.',
    victory: 'NULLIF! The Specter turns into a harmless, honest NULL and floats away.',
    timer: 120,
    phases: [{ name: 'Haunting', taunt: 'Minus one, minus one, forever unknown!', questions: ['w6-mb-1', 'w6-mb-2', 'w6-mb-3'] }],
  },
  boss: {
    id: 'w6-boss',
    name: 'The Duplicate Lead Hydra',
    sprite: 'hydra',
    mini: false,
    intro: 'The CRM shudders. A many-headed serpent bursts out of the March 2025 migration logs. Every head is a duplicate lead, and it grows more when you dedupe wrong!',
    victory: 'One head remains: the original. The Hydra shrinks into a single, well-behaved row. Devin adds a uniqueness test so it never comes back.',
    timer: 170,
    phases: [
      { name: 'Count the Heads', taunt: 'How many of me are there? Hsss!', questions: ['w6-b-1'] },
      { name: 'Wrong Cut', taunt: 'Keep the newest! It MUST be right!', questions: ['w6-b-2'] },
      { name: 'Last Heads', taunt: 'Your close rate will never be true!', questions: ['w6-b-3', 'w6-b-4'] },
    ],
  },
};
