import type { Challenge, World } from '../types';

const ACTIVE = '(termination_date IS NULL OR termination_date > as_of_date())';

export const W7_CHALLENGES: Challenge[] = [
  {
    id: 'w7-01',
    world: 7,
    type: 'write',
    title: 'Headcount Today',
    giver: 'jess',
    story: 'First thing every HR leader asks: how many people do we have, by department, as of today?',
    question: 'Return department and headcount (employees hired on or before as_of_date() and not terminated on or before it), largest first.',
    concepts: ['headcount', 'NULL', 'OR'],
    solution: `SELECT department, COUNT(*) AS headcount FROM employees WHERE hire_date <= as_of_date() AND ${ACTIVE} GROUP BY department ORDER BY headcount DESC`,
    orderMatters: true,
    expectedColumns: ['department', 'headcount'],
    hints: [
      'Active = no termination_date, or a termination_date in the future.',
      'Parentheses matter when you mix AND and OR!',
      'WHERE hire_date <= as_of_date() AND (termination_date IS NULL OR termination_date > as_of_date())',
    ],
    why: 'Headcount "as of a date" is the denominator for turnover, staffing ratios and cost per head. The NULL-means-still-here convention trips up a lot of queries.',
    codex: ['headcount'],
  },
  {
    id: 'w7-02',
    world: 7,
    type: 'write',
    title: "Who's the Boss?",
    giver: 'jess',
    story: "Denver's GM wants an up-to-date org chart: every current Denver employee and who they report to.",
    question: "For current (termination_date IS NULL) employees at location_id 1, return employee (first + ' ' + last), role and manager (the manager's first + ' ' + last name).",
    concepts: ['self-join', 'LEFT JOIN'],
    solution:
      "SELECT e.first_name || ' ' || e.last_name AS employee, e.role, m.first_name || ' ' || m.last_name AS manager FROM employees e LEFT JOIN employees m ON m.employee_id = e.manager_id WHERE e.location_id = 1 AND e.termination_date IS NULL",
    expectedColumns: ['employee', 'role', 'manager'],
    hints: ['Join the employees table to ITSELF with two aliases (e = employee, m = manager).', 'ON m.employee_id = e.manager_id', 'LEFT JOIN, so someone with no manager would still appear.'],
    why: 'Self-joins turn a manager_id pointer into a readable org chart. Look who manages Earl.',
  },
  {
    id: 'w7-03',
    world: 7,
    type: 'write',
    title: 'Tenure',
    giver: 'jess',
    story: 'How long do people stay in each role? Current employees only.',
    question: 'For current employees (no termination_date), return role, people (count) and avg_tenure_years (average of (as_of_date() − hire_date) ÷ 365.25), longest first.',
    concepts: ['date math', 'AVG', 'tenure'],
    solution: 'SELECT role, COUNT(*) AS people, AVG((as_of_date() - hire_date) / 365.25) AS avg_tenure_years FROM employees WHERE termination_date IS NULL GROUP BY role ORDER BY avg_tenure_years DESC',
    orderMatters: true,
    expectedColumns: ['role', 'people', 'avg_tenure_years'],
    hints: ['Days since hire ÷ 365.25 = years.', 'Average per role.', 'SELECT role, COUNT(*) AS people, AVG((as_of_date() - hire_date) / 365.25) AS avg_tenure_years FROM employees WHERE termination_date IS NULL GROUP BY role ORDER BY avg_tenure_years DESC'],
    why: 'Short tenure in sales is an industry-wide problem. Every departure costs recruiting, training and lost customer relationships. Techs tend to stay much longer.',
    codex: ['tenure'],
  },
  {
    id: 'w7-04',
    world: 7,
    type: 'write',
    title: 'Turnover 2025',
    giver: 'jess',
    story: 'The board wants our 2025 turnover rate: terminations in 2025 divided by average headcount (the average of the Jan 1 and Dec 31 headcounts).',
    question: 'Return terminations (in 2025), avg_headcount and turnover_pct (100 × terminations ÷ avg_headcount) in one row.',
    concepts: ['turnover', 'COUNT_IF', 'date ranges'],
    solution:
      "SELECT COUNT_IF(termination_date BETWEEN DATE '2025-01-01' AND DATE '2025-12-31') AS terminations, (COUNT_IF(hire_date <= DATE '2025-01-01' AND (termination_date IS NULL OR termination_date > DATE '2025-01-01')) + COUNT_IF(hire_date <= DATE '2025-12-31' AND (termination_date IS NULL OR termination_date > DATE '2025-12-31'))) / 2.0 AS avg_headcount, 100.0 * terminations / avg_headcount AS turnover_pct FROM employees",
    expectedColumns: ['terminations', 'avg_headcount', 'turnover_pct'],
    hints: [
      'Three COUNT_IFs over the same table: terms in 2025, headcount on Jan 1, headcount on Dec 31.',
      'DuckDB lets you reuse an alias from earlier in the same SELECT.',
      'Headcount on a date D: hire_date <= D AND (termination_date IS NULL OR termination_date > D)',
    ],
    why: '~45% is high, but not unusual for dealerships (sales and seasonal lot staff churn fast). Always state your turnover definition, because companies compute it differently.',
    codex: ['turnover'],
  },
  {
    id: 'w7-05',
    world: 7,
    type: 'write',
    title: 'Headcount Every Month',
    giver: 'jess',
    story: 'I need a headcount trend: the number of active employees at the end of every month in our data window.',
    question: 'Return month_end (last day of each month from July 2024 to June 2026) and headcount at that date.',
    concepts: ['generate_series', 'calendar table', 'LEFT JOIN', 'last_day'],
    starter: "SELECT last_day(d)::DATE AS month_end\nFROM generate_series(DATE '2024-07-01', DATE '2026-06-01', INTERVAL 1 MONTH) t(d)",
    solution:
      "SELECT m.month_end, COUNT(e.employee_id) AS headcount FROM (SELECT last_day(d)::DATE AS month_end FROM generate_series(DATE '2024-07-01', DATE '2026-06-01', INTERVAL 1 MONTH) t(d)) m LEFT JOIN employees e ON e.hire_date <= m.month_end AND (e.termination_date IS NULL OR e.termination_date > m.month_end) GROUP BY m.month_end ORDER BY m.month_end",
    orderMatters: true,
    expectedColumns: ['month_end', 'headcount'],
    hints: [
      'generate_series makes a calendar: one row per month. last_day() gives the month end.',
      'LEFT JOIN employees on a RANGE condition: hired by month_end and not yet terminated.',
      'COUNT(e.employee_id) per month_end (COUNT(*) would count 1 for an empty month).',
    ],
    why: 'A calendar table LEFT JOINed to your data fixes the "missing months" problem from the Sales Floor and handles date ranges. Watch the spring bumps: seasonal porters for RV-show season.',
    snowflake: [
      {
        title: 'Calendar rows',
        snowflake: "SELECT LAST_DAY(DATEADD(month, SEQ4(), '2024-07-01'::DATE)) AS month_end\nFROM TABLE(GENERATOR(ROWCOUNT => 24))",
        duckdb: "SELECT last_day(d)::DATE AS month_end\nFROM generate_series(DATE '2024-07-01', DATE '2026-06-01', INTERVAL 1 MONTH) t(d)",
      },
    ],
    codex: ['headcount'],
  },
  {
    id: 'w7-06',
    world: 7,
    type: 'write',
    title: 'Show Season Staffing',
    giver: 'jess',
    story: 'Every spring we hire seasonal lot porters for RV-show season. When do those hires land?',
    question: "Return month (DATE_TRUNC of hire_date) and seasonal_hires for employees with employment_type 'Seasonal', oldest first.",
    concepts: ['DATE_TRUNC', 'seasonality'],
    solution: "SELECT DATE_TRUNC('month', hire_date) AS month, COUNT(*) AS seasonal_hires FROM employees WHERE employment_type = 'Seasonal' GROUP BY month ORDER BY month",
    orderMatters: true,
    expectedColumns: ['month', 'seasonal_hires'],
    hints: ['Filter the employment type.', "Group by DATE_TRUNC('month', hire_date).", "SELECT DATE_TRUNC('month', hire_date) AS month, COUNT(*) AS seasonal_hires FROM employees WHERE employment_type = 'Seasonal' GROUP BY month ORDER BY month"],
    why: 'Staffing should lead demand: hire in February–April, before the spring rush, not during it.',
  },
  {
    id: 'w7-07',
    world: 7,
    type: 'write',
    title: 'Current Pay Rate',
    giver: 'jess',
    story: "pay_history keeps every raise. For the tech-pay review I need each current technician's LATEST hourly rate. (All numbers fictional!)",
    question: "For current technicians, return employee_id, name (first + ' ' + last), effective_date and rate of their most recent pay_history row, highest rate first.",
    concepts: ['QUALIFY', 'ROW_NUMBER', 'latest row per group'],
    solution:
      "SELECT e.employee_id, e.first_name || ' ' || e.last_name AS name, p.effective_date, p.rate FROM employees e JOIN pay_history p ON p.employee_id = e.employee_id WHERE e.role = 'Technician' AND e.termination_date IS NULL QUALIFY ROW_NUMBER() OVER (PARTITION BY e.employee_id ORDER BY p.effective_date DESC) = 1 ORDER BY p.rate DESC, e.employee_id",
    orderMatters: true,
    expectedColumns: ['employee_id', 'name', 'effective_date', 'rate'],
    hints: ['Join employees to pay_history.', "Number each person's rows newest-first and keep rn = 1.", 'QUALIFY ROW_NUMBER() OVER (PARTITION BY e.employee_id ORDER BY p.effective_date DESC) = 1'],
    why: '"Latest row per group" is one of the most common patterns in analytics: current price, current status, latest odometer reading...',
  },
  {
    id: 'w7-08',
    world: 7,
    type: 'write',
    title: 'The Whole Tree',
    giver: 'jess',
    story: 'Colleen Mayfield runs the Mountain region. How many CURRENT people roll up to her, at each level below her?',
    question: 'Starting from Colleen Mayfield (depth 0), return depth and people for every level of current employees under her (a recursive walk down manager_id).',
    concepts: ['recursive CTE', 'self-join', 'hierarchy'],
    starter:
      "WITH RECURSIVE org AS (\n  SELECT employee_id, 0 AS depth\n  FROM employees\n  WHERE first_name = 'Colleen' AND last_name = 'Mayfield'\n  UNION ALL\n  -- add the direct reports of everyone already in org\n)\nSELECT depth, COUNT(*) AS people FROM org GROUP BY depth ORDER BY depth",
    solution:
      "WITH RECURSIVE org AS (SELECT employee_id, 0 AS depth FROM employees WHERE first_name = 'Colleen' AND last_name = 'Mayfield' UNION ALL SELECT e.employee_id, o.depth + 1 FROM employees e JOIN org o ON e.manager_id = o.employee_id WHERE e.termination_date IS NULL) SELECT depth, COUNT(*) AS people FROM org GROUP BY depth ORDER BY depth",
    orderMatters: true,
    expectedColumns: ['depth', 'people'],
    hints: [
      'A recursive CTE = an anchor query UNION ALL a query that references the CTE itself.',
      'The recursive part joins employees whose manager_id is someone already in org.',
      'SELECT e.employee_id, o.depth + 1 FROM employees e JOIN org o ON e.manager_id = o.employee_id WHERE e.termination_date IS NULL',
    ],
    why: 'Hierarchies (org charts, bills of materials, account trees) need recursion. Both DuckDB and Snowflake support WITH RECURSIVE; Snowflake also has CONNECT BY.',
  },
  {
    id: 'w7-09',
    world: 7,
    type: 'fix',
    title: 'Where Did Everyone Go?',
    giver: 'jess',
    story: 'My active-employee count says ZERO. I assure you people still work here.',
    question: 'Fix the query so it counts current employees (no termination date, or a future one) as active.',
    concepts: ['NULL', 'OR'],
    starter: 'SELECT COUNT(*) AS active\nFROM employees\nWHERE termination_date > as_of_date()',
    solution: `SELECT COUNT(*) AS active FROM employees WHERE ${ACTIVE}`,
    expectedColumns: ['active'],
    hints: ['What is NULL > a date?', 'Current employees have NULL termination_date.', 'WHERE termination_date IS NULL OR termination_date > as_of_date()'],
    why: 'Comparisons with NULL are never true, so "termination_date > today" silently excludes everyone still employed. Always ask what NULL means in a column.',
    codex: ['null'],
  },
  {
    id: 'w7-10',
    world: 7,
    type: 'read',
    title: 'The Cohort Table',
    giver: 'jess',
    story: 'Rhonda loves this retention table for salespeople. Make sure you can explain one row of it.',
    question: 'What does retention_pct mean for a given hire_year?',
    concepts: ['cohorts', 'COUNT_IF'],
    query:
      "SELECT YEAR(hire_date) AS hire_year,\n       COUNT(*) AS hired,\n       COUNT_IF(termination_date IS NULL) AS still_here,\n       ROUND(100.0 * COUNT_IF(termination_date IS NULL) / COUNT(*), 1) AS retention_pct\nFROM employees\nWHERE role = 'Sales'\nGROUP BY hire_year\nORDER BY hire_year",
    choices: [
      'Of the salespeople hired that year, the percent still employed today',
      "Of today's salespeople, the percent who were hired that year",
      'The turnover rate during that year',
      "The percent of that year's hires who stayed at least 12 months",
    ],
    answer: 0,
    explanations: [
      "Yes: each row is a hiring cohort; still_here ÷ hired = today's survival rate of that cohort.",
      "The denominator is that year's hires, not today's headcount.",
      'Turnover uses terminations during a period over average headcount.',
      'Nothing measures a 12-month window; it compares to today.',
    ],
    hints: ['Each row = people hired in the same year (a cohort).', 'Numerator: still employed. Denominator: hired.', 'Measured as of today.'],
    why: 'Cohort tables separate "old hires stayed" from "new hires churn", which a single turnover number hides. Recent cohorts always look better because they have had less time to leave.',
  },

  // ---- bosses
  {
    id: 'w7-mb-1',
    world: 7,
    type: 'write',
    bossOnly: true,
    title: 'Org Chart 1',
    giver: 'jess',
    story: 'The Orphaned Org Chart has lost its top!',
    question: 'Return first_name, last_name and role of the employee with no manager.',
    concepts: ['IS NULL'],
    solution: 'SELECT first_name, last_name, role FROM employees WHERE manager_id IS NULL',
    hints: ['The top of the tree has no manager.', 'manager_id IS NULL', 'SELECT first_name, last_name, role FROM employees WHERE manager_id IS NULL'],
    why: 'Every tree has exactly one root (hopefully).',
  },
  {
    id: 'w7-mb-2',
    world: 7,
    type: 'write',
    bossOnly: true,
    title: 'Org Chart 2',
    giver: 'jess',
    story: "Count everyone's direct reports!",
    question: 'Return manager_id and direct_reports (count) for current employees, for managers with 5 or more current direct reports.',
    concepts: ['GROUP BY', 'HAVING'],
    solution: 'SELECT manager_id, COUNT(*) AS direct_reports FROM employees WHERE termination_date IS NULL AND manager_id IS NOT NULL GROUP BY manager_id HAVING COUNT(*) >= 5',
    hints: ['Group current employees by manager_id.', 'HAVING COUNT(*) >= 5', 'SELECT manager_id, COUNT(*) AS direct_reports FROM employees WHERE termination_date IS NULL AND manager_id IS NOT NULL GROUP BY manager_id HAVING COUNT(*) >= 5'],
    why: 'Span of control: how many direct reports each manager has.',
  },
  {
    id: 'w7-mb-3',
    world: 7,
    type: 'predict',
    bossOnly: true,
    title: 'Org Chart 3',
    giver: 'jess',
    story: 'A self-join riddle.',
    question: 'How many rows does this self-join return?',
    concepts: ['self-join', 'INNER JOIN'],
    query: 'SELECT e.employee_id, m.employee_id AS manager\nFROM employees e\nJOIN employees m ON m.employee_id = e.manager_id',
    measure: 'rows',
    decoys: [
      { sql: 'SELECT COUNT(*) FROM employees', why: 'The INNER JOIN drops the one employee with no manager.' },
      { sql: 'SELECT COUNT(DISTINCT manager_id) FROM employees', why: 'That counts managers, not employees with a manager.' },
      { sql: 'SELECT COUNT(*) FROM employees WHERE termination_date IS NULL', why: 'There is no filter on current employees here.' },
    ],
    explanation: 'Every employee who has a manager, which is everyone except the top of the tree.',
    hints: ['Each employee has at most one manager.', 'INNER JOIN drops non-matches.', 'Total minus one.'],
    why: 'Self-joins behave like any other join.',
  },
  {
    id: 'w7-b-1',
    world: 7,
    type: 'write',
    bossOnly: true,
    title: 'Tornado 1',
    giver: 'jess',
    story: 'The Turnover Tornado is sweeping people away! Where is it worst?',
    question: 'Return department and terms_2025 (terminations in 2025), biggest first.',
    concepts: ['COUNT_IF', 'turnover'],
    solution: "SELECT department, COUNT_IF(termination_date BETWEEN DATE '2025-01-01' AND DATE '2025-12-31') AS terms_2025 FROM employees GROUP BY department ORDER BY terms_2025 DESC, department",
    orderMatters: true,
    hints: ['COUNT_IF with a date range.', 'Group by department.', 'ORDER BY terms_2025 DESC'],
    why: 'Turnover by department points at where to invest in retention.',
  },
  {
    id: 'w7-b-2',
    world: 7,
    type: 'write',
    bossOnly: true,
    title: 'Tornado 2',
    giver: 'jess',
    story: 'Why do they leave?',
    question: 'Return termination_reason and people for all terminated employees, most common first.',
    concepts: ['GROUP BY'],
    solution: 'SELECT termination_reason, COUNT(*) AS people FROM employees WHERE termination_date IS NOT NULL GROUP BY termination_reason ORDER BY people DESC, termination_reason',
    orderMatters: true,
    hints: ['Only terminated employees.', 'Group by reason.', 'ORDER BY people DESC'],
    why: 'Voluntary vs involuntary turnover call for different fixes.',
  },
  {
    id: 'w7-b-3',
    world: 7,
    type: 'write',
    bossOnly: true,
    title: 'Tornado 3',
    giver: 'jess',
    story: 'Calm the storm: sales tenure at exit!',
    question: "For terminated employees with role 'Sales', return avg_tenure_days (average termination_date − hire_date).",
    concepts: ['date math', 'AVG'],
    solution: "SELECT AVG(termination_date - hire_date) AS avg_tenure_days FROM employees WHERE role = 'Sales' AND termination_date IS NOT NULL",
    hints: ['Date minus date = days.', 'Only terminated salespeople.', "SELECT AVG(termination_date - hire_date) AS avg_tenure_days FROM employees WHERE role = 'Sales' AND termination_date IS NOT NULL"],
    why: 'If most sales hires leave within a year, onboarding is the lever.',
  },
];

export const WORLD_7: World = {
  id: 7,
  name: 'People Ops',
  building: 'hr',
  giver: 'jess',
  tagline: 'Self-joins, date math, cohorts',
  concepts: ['self-join', 'recursive CTE', 'headcount', 'turnover', 'tenure', 'cohorts', 'generate_series'],
  lesson: [
    { title: 'People data, handled with care', body: 'HR data is sensitive. (Every name and number here is fictional.) The core concepts: headcount on a date, tenure (hire → today or termination), and turnover = terminations ÷ average headcount.' },
    { title: 'NULL means still here', body: 'termination_date IS NULL means the person is still employed. Any comparison with NULL is unknown, so "active" filters must say termination_date IS NULL OR termination_date > as_of_date().' },
    { title: 'Self-joins and recursion', body: 'manager_id points back into the same table. Join employees to itself to show manager names; use WITH RECURSIVE to walk the whole tree.', sql: 'SELECT e.last_name AS employee, m.last_name AS manager\nFROM employees e\nLEFT JOIN employees m ON m.employee_id = e.manager_id' },
  ],
  challenges: ['w7-01', 'w7-02', 'w7-03', 'w7-04', 'w7-05', 'w7-06', 'w7-07', 'w7-08', 'w7-09', 'w7-10'],
  miniBoss: {
    id: 'w7-mini',
    name: 'The Orphaned Org Chart',
    sprite: 'orgchart',
    mini: true,
    intro: 'A clipboard with legs stomps out of the HR office, trailing boxes and arrows that point nowhere. "WHO REPORTS TO WHOM?!"',
    victory: 'Every box finds its manager. The org chart folds itself neatly back into the filing cabinet.',
    timer: 120,
    phases: [{ name: 'Lost Boxes', taunt: 'Nobody knows who the boss is!', questions: ['w7-mb-1', 'w7-mb-2', 'w7-mb-3'] }],
  },
  boss: {
    id: 'w7-boss',
    name: 'The Turnover Tornado',
    sprite: 'tornado',
    mini: false,
    intro: 'Papers fly. Name badges spin in the air. The Turnover Tornado is sweeping through the sales floor, carrying new hires away!',
    victory: 'The winds die down. Jess picks up the badges and makes a plan: better onboarding, earlier check-ins. The tornado is gone.',
    timer: 150,
    phases: [
      { name: 'The Sweep', taunt: 'Where do they all go? Whoooosh!', questions: ['w7-b-1'] },
      { name: 'Why They Leave', taunt: 'Reasons? Who needs reasons!', questions: ['w7-b-2'] },
      { name: 'Eye of the Storm', taunt: 'They never stay long!', questions: ['w7-b-3'] },
    ],
  },
};
